import { readFile } from 'node:fs/promises';
import path from 'node:path';

import type { FastifyInstance } from 'fastify';

const learnPages = {
  '/learn/prd': {
    fileName: 'PRD.html',
    title: 'Interactive PRD'
  },
  '/learn/developer-workbench': {
    fileName: 'PRD-Design-Dev-Workbench.html',
    title: 'Developer Workbench Preview'
  }
} as const;

function buildReviewQueuePage(): string {
  return [
    '<!DOCTYPE html>',
    '<html lang="en">',
    '<head>',
    '  <meta charset="utf-8" />',
    '  <meta name="viewport" content="width=device-width, initial-scale=1" />',
    '  <title>Nexus Review Queue</title>',
    '  <style>',
    '    :root { color-scheme: light; --bg-top: #f8f1dd; --bg-bottom: #d7e2db; --ink: #18212b; --muted: rgba(24,33,43,0.68); --panel: rgba(255,255,255,0.84); --panel-strong: rgba(255,255,255,0.94); --line: rgba(24,33,43,0.12); --accent: #0d5e55; --accent-soft: rgba(13,94,85,0.12); --accent-ink: #0a3d37; --good: #0f6b46; --bad: #922f2f; --warn: #8b6208; --shadow: 0 22px 56px rgba(24,33,43,0.12); }',
    '    * { box-sizing: border-box; }',
    '    body { margin: 0; font-family: "Iowan Old Style", Georgia, serif; color: var(--ink); background: radial-gradient(circle at top left, #fff8eb 0%, var(--bg-top) 36%, var(--bg-bottom) 100%); }',
    '    main { max-width: 1340px; margin: 0 auto; padding: 36px 18px 60px; }',
    '    h1 { margin: 0 0 10px; font-size: clamp(2.7rem, 5vw, 5rem); line-height: 0.92; max-width: 12ch; }',
    '    p { color: var(--muted); max-width: 76ch; line-height: 1.6; }',
    '    .eyebrow { display: inline-block; margin-bottom: 14px; padding: 8px 10px; border-radius: 999px; background: var(--accent-soft); color: var(--accent); font: 600 0.76rem/1.1 ui-monospace, SFMono-Regular, Menlo, monospace; text-transform: uppercase; letter-spacing: 0.08em; }',
    '    .hero { display: grid; gap: 20px; }',
    '    .hero-grid { display: grid; grid-template-columns: minmax(0, 1.5fr) minmax(280px, 0.9fr); gap: 18px; align-items: end; }',
    '    .summary-grid { display: grid; grid-template-columns: repeat(4, minmax(0, 1fr)); gap: 14px; }',
    '    .summary-card { background: linear-gradient(180deg, rgba(255,255,255,0.95), rgba(255,255,255,0.76)); border: 1px solid rgba(255,255,255,0.5); border-radius: 24px; padding: 18px; box-shadow: var(--shadow); min-height: 120px; }',
    '    .summary-label { display: block; color: var(--muted); font: 600 0.78rem/1.2 ui-monospace, SFMono-Regular, Menlo, monospace; text-transform: uppercase; letter-spacing: 0.08em; }',
    '    .summary-value { display: block; margin-top: 10px; font-size: clamp(1.8rem, 4vw, 3rem); line-height: 0.95; }',
    '    .summary-note { margin-top: 10px; font-size: 0.95rem; color: var(--muted); }',
    '    .shell { display: grid; grid-template-columns: 390px minmax(0, 1fr); gap: 18px; margin-top: 28px; }',
    '    .panel { background: var(--panel); border: 1px solid var(--line); border-radius: 28px; box-shadow: var(--shadow); overflow: hidden; backdrop-filter: blur(10px); }',
    '    .controls { padding: 18px; display: grid; gap: 12px; }',
    '    label { display: grid; gap: 6px; font-size: 0.92rem; color: var(--muted); }',
    '    input, textarea, button, select { font: inherit; }',
    '    input, textarea, select { width: 100%; border: 1px solid var(--line); border-radius: 14px; padding: 11px 12px; background: var(--panel-strong); color: var(--ink); }',
    '    textarea { min-height: 96px; resize: vertical; }',
    '    button { border: none; border-radius: 14px; padding: 12px 14px; cursor: pointer; transition: transform 140ms ease, opacity 140ms ease; }',
    '    button:hover { transform: translateY(-1px); }',
    '    button.primary { background: var(--accent); color: #fffaf6; }',
    '    button.secondary { background: rgba(255,255,255,0.86); border: 1px solid var(--line); color: var(--ink); }',
    '    button.success { background: var(--good); color: white; }',
    '    button.danger { background: var(--bad); color: white; }',
    '    button:disabled { opacity: 0.5; cursor: not-allowed; transform: none; }',
    '    .list { display: grid; gap: 10px; padding: 0 18px 18px; max-height: 640px; overflow: auto; }',
    '    .item { width: 100%; text-align: left; border: 1px solid var(--line); border-radius: 20px; padding: 14px; background: rgba(255,255,255,0.72); cursor: pointer; }',
    '    .item.active { border-color: rgba(13,94,85,0.45); box-shadow: inset 0 0 0 1px rgba(13,94,85,0.2); background: rgba(239,249,246,0.96); }',
    '    .item-header { display: flex; gap: 10px; align-items: flex-start; }',
    '    .item-check { margin-top: 2px; width: 18px; height: 18px; accent-color: var(--accent); }',
    '    .item h3 { margin: 0 0 8px; font-size: 1.04rem; }',
    '    .meta { display: flex; flex-wrap: wrap; gap: 8px; font-size: 0.8rem; color: var(--muted); }',
    '    .badge { display: inline-flex; align-items: center; gap: 6px; border-radius: 999px; padding: 6px 9px; background: #eef4f2; }',
    '    .stack { display: grid; gap: 14px; }',
    '    .summary-strip { display: grid; gap: 10px; grid-template-columns: repeat(auto-fit, minmax(180px, 1fr)); }',
    '    .mini-card { border: 1px solid var(--line); border-radius: 18px; padding: 14px; background: rgba(255,255,255,0.78); }',
    '    .bulk-box { display: grid; gap: 10px; }',
    '    .project-pills { display: flex; flex-wrap: wrap; gap: 10px; }',
    '    .project-pill { border: 1px solid var(--line); background: rgba(255,255,255,0.72); color: var(--ink); padding: 10px 12px; border-radius: 16px; text-align: left; }',
    '    .project-pill.active { background: rgba(13,94,85,0.14); border-color: rgba(13,94,85,0.35); color: var(--accent-ink); }',
    '    .workspace { padding: 18px; display: grid; gap: 16px; min-height: 760px; }',
    '    .workspace pre { margin: 0; padding: 14px; border-radius: 16px; background: #231f20; color: #f7efe3; overflow: auto; font: 0.82rem/1.45 ui-monospace, SFMono-Regular, Menlo, monospace; }',
    '    .empty { display: grid; place-items: center; min-height: 280px; color: var(--muted); border: 1px dashed var(--line); border-radius: 18px; }',
    '    .split { display: grid; grid-template-columns: repeat(2, minmax(0, 1fr)); gap: 14px; }',
    '    .status { padding: 12px 14px; border-top: 1px solid var(--line); background: rgba(31,36,48,0.03); color: var(--muted); min-height: 48px; }',
    '    .row { display: flex; gap: 10px; flex-wrap: wrap; }',
    '    .row.spread { justify-content: space-between; align-items: center; }',
    '    .section-title { margin: 0; font-size: 0.9rem; letter-spacing: 0.04em; text-transform: uppercase; color: var(--muted); }',
    '    .helper { font-size: 0.85rem; color: var(--muted); }',
    '    .pager { display: flex; gap: 10px; align-items: center; justify-content: space-between; padding: 0 18px 18px; }',
    '    .pager-group { display: flex; gap: 10px; align-items: center; }',
    '    @media (max-width: 1120px) { .hero-grid, .shell, .split { grid-template-columns: 1fr; } .summary-grid { grid-template-columns: repeat(2, minmax(0, 1fr)); } }',
    '    @media (max-width: 680px) { .summary-grid { grid-template-columns: 1fr; } main { padding-inline: 12px; } }',
    '  </style>',
    '</head>',
    '<body>',
    '  <main>',
    '    <section class="hero">',
    '      <span class="eyebrow">Operator Review Console</span>',
    '      <div class="hero-grid">',
    '        <div>',
    '          <h1>Review hosted feedback before it lands in GitHub.</h1>',
    '          <p>This queue now pages through pending hosted feedback, surfaces project-level hotspots, and lets an operator approve or reject each draft using the same internal review endpoints the control plane exposes.</p>',
    '        </div>',
    '        <div class="summary-grid">',
    '          <article class="summary-card"><span class="summary-label">Queued</span><span id="queuedCount" class="summary-value">0</span><span class="summary-note" id="queuedNote">Pending reports across the current filter.</span></article>',
    '          <article class="summary-card"><span class="summary-label">Critical</span><span id="criticalCount" class="summary-value">0</span><span class="summary-note">Critical hosted feedback waiting on review.</span></article>',
    '          <article class="summary-card"><span class="summary-label">Projects</span><span id="projectCount" class="summary-value">0</span><span class="summary-note">Projects represented in this queue slice.</span></article>',
    '          <article class="summary-card"><span class="summary-label">Page</span><span id="pageValue" class="summary-value">1</span><span class="summary-note" id="pageNote">Queue page and sort state.</span></article>',
    '        </div>',
    '      </div>',
    '    </section>',
    '    <section class="shell">',
    '      <aside class="panel">',
    '        <div class="controls">',
    '          <label>Base URL<input id="baseUrl" value="" placeholder="http://127.0.0.1:4000" /></label>',
    '          <label>Bearer Token<input id="token" value="" placeholder="nexus-local-dev-token" /></label>',
    '          <label>Project Id Filter<input id="projectId" value="" placeholder="Optional project UUID" /></label>',
    '          <label>Assigned To<input id="assignedTo" value="" placeholder="Filter by reviewer or operator id" /></label>',
    '          <label>Search Queue<input id="search" value="" placeholder="Project, repo, title, reporter" /></label>',
    '          <label>Sort By<select id="sort"><option value="newest">Newest first</option><option value="oldest">Oldest first</option><option value="impact">Highest impact</option><option value="severity">Highest severity</option></select></label>',
    '          <div class="row">',
    '            <button id="refresh" class="primary">Refresh Queue</button>',
    '            <button id="clearToken" class="secondary">Clear Saved Auth</button>',
    '          </div>',
    '          <div class="stack">',
    '            <h2 class="section-title">Project Hotspots</h2>',
    '            <div id="projectSummaries" class="project-pills"></div>',
    '          </div>',
    '          <div class="bulk-box">',
    '            <h2 class="section-title">Bulk Actions</h2>',
    '            <label>Assign Selected To<input id="bulkReviewerId" value="" placeholder="defaults to your operator id" /></label>',
    '            <label>Bulk Repository Override<input id="bulkRepository" value="" placeholder="owner/repo optional" /></label>',
    '            <label>Bulk Notes<textarea id="bulkNotes" placeholder="Applied to selected queued reports."></textarea></label>',
    '            <div class="row">',
    '              <button id="assignSelected" class="secondary">Assign</button>',
    '              <button id="approveSelected" class="success">Approve</button>',
    '              <button id="rejectSelected" class="danger">Reject</button>',
    '              <button id="clearSelection" class="secondary">Clear</button>',
    '            </div>',
    '          </div>',
    '        </div>',
    '        <div id="queue" class="list"></div>',
    '        <div class="pager">',
    '          <div class="pager-group">',
    '            <button id="previousPage" class="secondary">Previous</button>',
    '            <button id="nextPage" class="secondary">Next</button>',
    '          </div>',
    '          <div class="helper" id="pageSummary">Page 1</div>',
    '        </div>',
    '        <div id="queueStatus" class="status">Queue not loaded yet.</div>',
    '      </aside>',
    '      <section class="panel workspace">',
    '        <div class="summary-strip">',
    '          <article class="mini-card"><h2 class="section-title">Severity Mix</h2><div id="severitySummary" class="helper">No queue data loaded yet.</div></article>',
    '          <article class="mini-card"><h2 class="section-title">Filter State</h2><div id="filterSummary" class="helper">No filters applied.</div></article>',
    '          <article class="mini-card"><h2 class="section-title">Queue Window</h2><div id="windowSummary" class="helper">Waiting for queue data.</div></article>',
    '        </div>',
    '        <div class="split">',
    '          <div>',
    '            <h2 class="section-title">Selected Report</h2>',
    '            <div id="summary" class="empty">Select a queued report to inspect context.</div>',
    '          </div>',
    '          <div>',
    '            <h2 class="section-title">Decision</h2>',
    '            <label>Repository Override<input id="repository" value="" placeholder="owner/repo optional" /></label>',
    '            <label>Notes<textarea id="notes" placeholder="Record why this was approved or rejected."></textarea></label>',
    '            <div class="row">',
    '              <button id="approve" class="success" disabled>Approve</button>',
    '              <button id="reject" class="danger" disabled>Reject</button>',
    '            </div>',
    '          </div>',
    '        </div>',
    '        <div>',
    '          <h2 class="section-title">Context</h2>',
    '          <pre id="context">// report context appears here</pre>',
    '        </div>',
    '      </section>',
    '    </section>',
    '  </main>',
    '  <script>',
    '    const storageKey = "nexus-review-queue-auth";',
    '    const state = { items: [], selected: null, selectedIds: [], context: null, summary: null, filters: { page: 1, limit: 12, sort: "newest", projectId: "", assignedTo: "", search: "" } };',
    '    const els = {',
    '      baseUrl: document.getElementById("baseUrl"),',
    '      token: document.getElementById("token"),',
    '      projectId: document.getElementById("projectId"),',
    '      assignedTo: document.getElementById("assignedTo"),',
    '      search: document.getElementById("search"),',
    '      sort: document.getElementById("sort"),',
    '      refresh: document.getElementById("refresh"),',
    '      clearToken: document.getElementById("clearToken"),',
    '      previousPage: document.getElementById("previousPage"),',
    '      nextPage: document.getElementById("nextPage"),',
    '      queue: document.getElementById("queue"),',
    '      queueStatus: document.getElementById("queueStatus"),',
    '      bulkReviewerId: document.getElementById("bulkReviewerId"),',
    '      bulkRepository: document.getElementById("bulkRepository"),',
    '      bulkNotes: document.getElementById("bulkNotes"),',
    '      assignSelected: document.getElementById("assignSelected"),',
    '      approveSelected: document.getElementById("approveSelected"),',
    '      rejectSelected: document.getElementById("rejectSelected"),',
    '      clearSelection: document.getElementById("clearSelection"),',
    '      projectSummaries: document.getElementById("projectSummaries"),',
    '      pageSummary: document.getElementById("pageSummary"),',
    '      queuedCount: document.getElementById("queuedCount"),',
    '      queuedNote: document.getElementById("queuedNote"),',
    '      criticalCount: document.getElementById("criticalCount"),',
    '      projectCount: document.getElementById("projectCount"),',
    '      pageValue: document.getElementById("pageValue"),',
    '      pageNote: document.getElementById("pageNote"),',
    '      severitySummary: document.getElementById("severitySummary"),',
    '      filterSummary: document.getElementById("filterSummary"),',
    '      windowSummary: document.getElementById("windowSummary"),',
    '      summary: document.getElementById("summary"),',
    '      repository: document.getElementById("repository"),',
    '      notes: document.getElementById("notes"),',
    '      approve: document.getElementById("approve"),',
    '      reject: document.getElementById("reject"),',
    '      context: document.getElementById("context")',
    '    };',
    '    function readSaved() {',
    '      try { return JSON.parse(localStorage.getItem(storageKey) || "{}"); } catch { return {}; }',
    '    }',
    '    function saveAuth() {',
    '      localStorage.setItem(storageKey, JSON.stringify({ baseUrl: els.baseUrl.value.trim(), token: els.token.value.trim(), projectId: els.projectId.value.trim(), assignedTo: els.assignedTo.value.trim(), search: els.search.value.trim(), sort: els.sort.value }));',
    '    }',
    '    function setStatus(message) { els.queueStatus.textContent = message; }',
    '    function authHeaders() {',
    '      const token = els.token.value.trim();',
    '      return token ? { Authorization: `Bearer ${token}` } : {};',
    '    }',
    '    function escapeHtml(value) {',
    '      return String(value ?? "").replace(/[&<>"\']/g, (character) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", "\"": "&quot;", "\'": "&#39;" }[character] || character));',
    '    }',
    '    function relativeTime(value) {',
    '      if (!value) return "unknown";',
    '      const milliseconds = Date.now() - new Date(value).getTime();',
    '      const minutes = Math.round(milliseconds / 60000);',
    '      if (!Number.isFinite(minutes)) return "unknown";',
    '      if (Math.abs(minutes) < 60) return `${minutes}m ago`;',
    '      const hours = Math.round(minutes / 60);',
    '      if (Math.abs(hours) < 48) return `${hours}h ago`;',
    '      const days = Math.round(hours / 24);',
    '      return `${days}d ago`;',
    '    }',
    '    function isSelected(reportId) { return state.selectedIds.includes(reportId); }',
    '    function clearSelection() { state.selectedIds = []; renderQueue(); renderSummary(); }',
    '    function toggleSelection(reportId) {',
    '      state.selectedIds = isSelected(reportId) ? state.selectedIds.filter((id) => id !== reportId) : [...state.selectedIds, reportId];',
    '      renderQueue();',
    '      renderSummary();',
    '    }',
    '    async function request(path, init) {',
    '      const baseUrl = els.baseUrl.value.trim() || window.location.origin;',
    '      const response = await fetch(baseUrl + path, init);',
    '      const text = await response.text();',
    '      if (!response.ok) { throw new Error(`${init && init.method ? init.method : "GET"} ${path} failed: ${response.status} ${text}`); }',
    '      return JSON.parse(text);',
    '    }',
    '    function renderSummary() {',
    '      const summary = state.summary;',
    '      const filters = state.filters;',
    '      const severityCounts = summary && summary.severityCounts ? summary.severityCounts : {};',
    '      const projectSummaries = summary && Array.isArray(summary.projectSummaries) ? summary.projectSummaries : [];',
    '      els.queuedCount.textContent = String(summary ? summary.totalItems : 0);',
    '      els.criticalCount.textContent = String(severityCounts.critical || 0);',
    '      els.projectCount.textContent = String(projectSummaries.length);',
    '      els.pageValue.textContent = String(filters.page);',
    '      els.pageNote.textContent = `${filters.sort} order | ${state.selectedIds.length} selected`;',
    '      els.queuedNote.textContent = summary ? `${summary.totalPages} page${summary.totalPages === 1 ? "" : "s"} in current queue filter.` : "Pending reports across the current filter.";',
    '      const severityText = Object.entries(severityCounts).length ? Object.entries(severityCounts).map(([key, value]) => `${key}: ${value}`).join(" | ") : "No queue data loaded yet.";',
    '      els.severitySummary.textContent = severityText;',
    '      const activeFilters = [filters.projectId ? `project ${filters.projectId}` : null, filters.assignedTo ? `assigned ${filters.assignedTo}` : null, filters.search ? `search \"${filters.search}\"` : null].filter(Boolean).join(" | ") || "No filters applied.";',
    '      els.filterSummary.textContent = activeFilters;',
    '      els.windowSummary.textContent = summary ? `${state.items.length} item${state.items.length === 1 ? "" : "s"} shown on page ${filters.page} of ${summary.totalPages}.` : "Waiting for queue data.";',
    '      els.pageSummary.textContent = summary ? `Page ${filters.page} of ${summary.totalPages}` : `Page ${filters.page}`;',
    '      els.previousPage.disabled = filters.page <= 1;',
    '      els.nextPage.disabled = !(summary && summary.hasNextPage);',
    '      els.projectSummaries.innerHTML = "";',
    '      const allButton = document.createElement("button");',
    '      allButton.type = "button";',
    '      allButton.className = `project-pill${filters.projectId ? "" : " active"}`;',
    '      allButton.textContent = `All projects (${summary ? summary.totalItems : 0})`;',
    '      allButton.addEventListener("click", () => { state.filters.page = 1; els.projectId.value = ""; loadQueue(); });',
    '      els.projectSummaries.appendChild(allButton);',
    '      for (const entry of projectSummaries) {',
    '        const button = document.createElement("button");',
    '        button.type = "button";',
    '        const projectId = entry.project && entry.project.id ? entry.project.id : "";',
    '        button.className = `project-pill${projectId && projectId === filters.projectId ? " active" : ""}`;',
    '        button.innerHTML = `<strong>${escapeHtml(entry.project ? entry.project.name : "Unscoped")}</strong><br /><span class="helper">${entry.queuedCount} queued | impact ${entry.highestImpactScore ?? "n/a"}</span>`;',
    '        button.addEventListener("click", () => { state.filters.page = 1; els.projectId.value = projectId; loadQueue(); });',
    '        els.projectSummaries.appendChild(button);',
    '      }',
    '    }',
    '    function renderQueue() {',
    '      els.queue.innerHTML = "";',
    '      if (!state.items.length) {',
    '        const empty = document.createElement("div");',
    '        empty.className = "empty";',
    '        empty.textContent = "No queued hosted-feedback reviews found.";',
    '        els.queue.appendChild(empty);',
    '        return;',
    '      }',
    '      for (const item of state.items) {',
    '        const card = document.createElement("button");',
    '        card.type = "button";',
    '        card.className = `item${state.selected && state.selected.reportId === item.reportId ? " active" : ""}`;',
    '        card.innerHTML = [`<div class="item-header"><input class="item-check" data-role="select" type="checkbox" ${isSelected(item.reportId) ? "checked" : ""} /><div><h3>${escapeHtml(item.title || item.reportId)}</h3><div class="meta"><span class="badge">${escapeHtml(item.project ? item.project.name : "Unscoped project")}</span><span class="badge">${escapeHtml(item.severity)}</span><span class="badge">impact ${item.impactScore ?? "n/a"}</span><span class="badge">${escapeHtml(relativeTime(item.createdAt))}</span></div><div class="helper">${escapeHtml(item.repository || "repository unresolved")} | ${escapeHtml(item.reporterIdentifier || "anonymous")} | assigned ${escapeHtml(item.assignedReviewerId || "unassigned")}</div></div></div>`].join("");',
    '        const checkbox = card.querySelector("[data-role=select]");',
    '        if (checkbox) { checkbox.addEventListener("click", (event) => { event.stopPropagation(); }); checkbox.addEventListener("change", () => toggleSelection(item.reportId)); }',
    '        card.addEventListener("click", () => selectItem(item));',
    '        els.queue.appendChild(card);',
    '      }',
    '    }',
    '    function renderSelection() {',
    '      const selected = state.selected;',
    '      const context = state.context;',
    '      const actionable = Boolean(selected);',
    '      els.approve.disabled = !actionable;',
    '      els.reject.disabled = !actionable;',
    '      if (!selected) {',
    '        els.summary.className = "empty";',
    '        els.summary.textContent = "Select a queued report to inspect context.";',
    '        els.context.textContent = "// report context appears here";',
    '        return;',
    '      }',
    '      els.summary.className = "";',
    '      els.summary.innerHTML = [`<div class="row">`,`<span class="badge">${escapeHtml(selected.reportId)}</span>`,`<span class="badge">${escapeHtml(selected.repository || "repository unresolved")}</span>`,`<span class="badge">${escapeHtml(selected.severity)}</span>`,`<span class="badge">assigned ${escapeHtml(selected.assignedReviewerId || "unassigned")}</span>`,`</div>`,`<p><strong>${escapeHtml(selected.title)}</strong></p>`,`<p>${selected.project ? `${escapeHtml(selected.project.name)} (${escapeHtml(selected.project.projectKey)})` : "No project metadata"}</p>`,`<p>Reporter: ${escapeHtml(selected.reporterIdentifier || "anonymous")}</p>`,`<p class="helper">Created ${escapeHtml(relativeTime(selected.createdAt))} | Updated ${escapeHtml(relativeTime(selected.updatedAt))}</p>`].join("");',
    '      els.repository.value = selected.repository || "";',
    '      els.context.textContent = JSON.stringify(context || {}, null, 2);',
    '    }',
    '    async function loadQueue() {',
    '      saveAuth();',
    '      setStatus("Loading review queue...");',
    '      state.filters.projectId = els.projectId.value.trim();',
    '      state.filters.assignedTo = els.assignedTo.value.trim();',
    '      state.filters.search = els.search.value.trim();',
    '      state.filters.sort = els.sort.value;',
    '      const params = new URLSearchParams();',
    '      if (state.filters.projectId) params.set("projectId", state.filters.projectId);',
    '      if (state.filters.assignedTo) params.set("assignedTo", state.filters.assignedTo);',
    '      if (state.filters.search) params.set("search", state.filters.search);',
    '      params.set("page", String(state.filters.page));',
    '      params.set("limit", String(state.filters.limit));',
    '      params.set("sort", state.filters.sort);',
    '      try {',
    '        const data = await request(`/internal/reports/review-queue?${params.toString()}`, { headers: authHeaders() });',
    '        state.items = Array.isArray(data.items) ? data.items : [];',
    '        state.summary = data.summary || null;',
    '        state.selectedIds = state.selectedIds.filter((reportId) => state.items.some((item) => item.reportId === reportId));',
    '        state.filters.page = data.filters && typeof data.filters.page === "number" ? data.filters.page : state.filters.page;',
    '        if (state.selected) {',
    '          state.selected = state.items.find((item) => item.reportId === state.selected.reportId) || null;',
    '        }',
    '        renderSummary();',
    '        renderQueue();',
    '        renderSelection();',
    '        setStatus(`Loaded ${state.items.length} queued report${state.items.length === 1 ? "" : "s"} on page ${state.filters.page}.`);',
    '      } catch (error) {',
    '        state.summary = null;',
    '        renderSummary();',
    '        setStatus(error instanceof Error ? error.message : "Failed to load queue.");',
    '      }',
    '    }',
    '    async function selectItem(item) {',
    '      state.selected = item;',
    '      renderQueue();',
    '      setStatus(`Loading context for ${item.reportId}...`);',
    '      try {',
    '        state.context = await request(item.contextPath, { headers: authHeaders() });',
    '        renderSelection();',
    '        setStatus(`Loaded context for ${item.reportId}.`);',
    '      } catch (error) {',
    '        state.context = null;',
    '        renderSelection();',
    '        setStatus(error instanceof Error ? error.message : "Failed to load report context.");',
    '      }',
    '    }',
    '    async function submitReview(status) {',
    '      if (!state.selected) return;',
    '      setStatus(`${status === "approved" ? "Approving" : "Rejecting"} ${state.selected.reportId}...`);',
    '      try {',
    '        const payload = { status, notes: els.notes.value.trim() || undefined, repository: status === "approved" ? (els.repository.value.trim() || undefined) : undefined };',
    '        const result = await request(`/internal/reports/${state.selected.reportId}/review`, { method: "POST", headers: { "content-type": "application/json", ...authHeaders() }, body: JSON.stringify(payload) });',
    '        els.notes.value = "";',
    '        state.context = result;',
    '        await loadQueue();',
    '        setStatus(`${state.selected ? state.selected.reportId : "Report"} ${status}.`);',
    '      } catch (error) {',
    '        setStatus(error instanceof Error ? error.message : "Failed to submit review.");',
    '      }',
    '    }',
    '    async function submitBulkAction(action) {',
    '      if (!state.selectedIds.length) { setStatus("Select at least one queued report first."); return; }',
    '      setStatus(`${action} ${state.selectedIds.length} queued report(s)...`);',
    '      const payload = {',
    '        action,',
    '        reportIds: state.selectedIds,',
    '        reviewerId: action === "assign" ? (els.bulkReviewerId.value.trim() || undefined) : undefined,',
    '        repository: action === "approve" ? (els.bulkRepository.value.trim() || undefined) : undefined,',
    '        notes: els.bulkNotes.value.trim() || undefined',
    '      };',
    '      try {',
    '        await request(`/internal/reports/review-queue/actions`, { method: "POST", headers: { "content-type": "application/json", ...authHeaders() }, body: JSON.stringify(payload) });',
    '        els.bulkNotes.value = "";',
    '        if (action !== "assign") { els.bulkRepository.value = ""; }',
    '        clearSelection();',
    '        await loadQueue();',
    '        setStatus(`Bulk ${action} completed.`);',
    '      } catch (error) {',
    '        setStatus(error instanceof Error ? error.message : `Bulk ${action} failed.`);',
    '      }',
    '    }',
    '    const saved = readSaved();',
    '    els.baseUrl.value = saved.baseUrl || window.location.origin;',
    '    els.token.value = saved.token || "";',
    '    els.projectId.value = saved.projectId || "";',
    '    els.assignedTo.value = saved.assignedTo || "";',
    '    els.search.value = saved.search || "";',
    '    els.sort.value = saved.sort || "newest";',
    '    state.filters.projectId = els.projectId.value.trim();',
    '    state.filters.assignedTo = els.assignedTo.value.trim();',
    '    state.filters.search = els.search.value.trim();',
    '    state.filters.sort = els.sort.value;',
    '    els.refresh.addEventListener("click", () => { state.filters.page = 1; loadQueue(); });',
    '    els.clearToken.addEventListener("click", () => { localStorage.removeItem(storageKey); els.token.value = ""; setStatus("Saved auth cleared."); });',
    '    els.previousPage.addEventListener("click", () => { if (state.filters.page > 1) { state.filters.page -= 1; loadQueue(); } });',
    '    els.nextPage.addEventListener("click", () => { state.filters.page += 1; loadQueue(); });',
    '    els.assignedTo.addEventListener("keydown", (event) => { if (event.key === "Enter") { state.filters.page = 1; loadQueue(); } });',
    '    els.search.addEventListener("keydown", (event) => { if (event.key === "Enter") { state.filters.page = 1; loadQueue(); } });',
    '    els.sort.addEventListener("change", () => { state.filters.page = 1; loadQueue(); });',
    '    els.approve.addEventListener("click", () => submitReview("approved"));',
    '    els.reject.addEventListener("click", () => submitReview("rejected"));',
    '    els.assignSelected.addEventListener("click", () => submitBulkAction("assign"));',
    '    els.approveSelected.addEventListener("click", () => submitBulkAction("approve"));',
    '    els.rejectSelected.addEventListener("click", () => submitBulkAction("reject"));',
    '    els.clearSelection.addEventListener("click", clearSelection);',
    '    renderSummary();',
    '  </script>',
    '</body>',
    '</html>'
  ].join('\n');
}

async function readLearnPage(fileName: string): Promise<string> {
  return readFile(path.resolve(process.cwd(), fileName), 'utf8');
}

function logUnavailablePage(app: FastifyInstance, routePath: string, title: string, error: unknown): void {
  app.log.warn({ err: error, routePath, title }, 'learn page unavailable');
}

export function registerLearnRoutes(app: FastifyInstance): void {
  app.get('/learn', async (_request, reply) => {
    reply.type('text/html; charset=utf-8');

    return [
      '<!DOCTYPE html>',
      '<html lang="en">',
      '<head>',
      '  <meta charset="utf-8" />',
      '  <meta name="viewport" content="width=device-width, initial-scale=1" />',
      '  <title>Nexus Learn More</title>',
      '  <style>',
      '    :root { color-scheme: light; --bg: #f4efe7; --ink: #1e2430; --card: rgba(255,255,255,0.82); --accent: #0b6e4f; --accent-soft: #d7efe6; }',
      '    * { box-sizing: border-box; }',
      '    body { margin: 0; font-family: Georgia, "Iowan Old Style", serif; background: radial-gradient(circle at top, #fff9ef 0%, var(--bg) 52%, #e4dccf 100%); color: var(--ink); }',
      '    main { max-width: 960px; margin: 0 auto; padding: 72px 24px 96px; }',
      '    h1 { font-size: clamp(2.6rem, 7vw, 5rem); line-height: 0.95; margin: 0 0 16px; }',
      '    p { max-width: 60ch; font-size: 1.08rem; line-height: 1.6; }',
      '    .grid { display: grid; gap: 18px; margin-top: 36px; }',
      '    .card { display: block; text-decoration: none; color: inherit; background: var(--card); border: 1px solid rgba(30,36,48,0.1); border-radius: 22px; padding: 24px; box-shadow: 0 20px 45px rgba(30,36,48,0.08); transition: transform 180ms ease, box-shadow 180ms ease; }',
      '    .card:hover { transform: translateY(-3px); box-shadow: 0 24px 54px rgba(30,36,48,0.12); }',
      '    .eyebrow { display: inline-block; font: 600 0.78rem/1.2 ui-monospace, SFMono-Regular, Menlo, monospace; letter-spacing: 0.08em; text-transform: uppercase; color: var(--accent); background: var(--accent-soft); padding: 8px 10px; border-radius: 999px; }',
      '    .title { display: block; font-size: 1.6rem; margin: 14px 0 8px; }',
      '    .hint { color: rgba(30,36,48,0.74); }',
      '  </style>',
      '</head>',
      '<body>',
      '  <main>',
      '    <span class="eyebrow">Nexus Learn More</span>',
      '    <h1>Explore the product story and developer workbench.</h1>',
      '    <p>These pages are hosted directly from the gateway so prospective users and contributors can review the product rationale and the Phase 7 developer experience without cloning the repo first.</p>',
      '    <section class="grid">',
      '      <a class="card" href="/learn/prd">',
      '        <span class="title">Interactive PRD</span>',
      '        <span class="hint">Product narrative, scope, and operating model.</span>',
      '      </a>',
      '      <a class="card" href="/learn/developer-workbench">',
      '        <span class="title">Developer Workbench Preview</span>',
      '        <span class="hint">Phase 7+ design concepts for MCP-assisted triage and repair.</span>',
      '      </a>',
      '      <a class="card" href="/learn/review-queue">',
      '        <span class="title">Operator Review Console</span>',
      '        <span class="hint">Review hosted feedback, inspect context, and approve or reject GitHub issue creation.</span>',
      '      </a>',
      '    </section>',
      '  </main>',
      '</body>',
      '</html>'
    ].join('\n');
  });

  for (const [routePath, page] of Object.entries(learnPages)) {
    app.get(routePath, async (_request, reply) => {
      try {
        const html = await readLearnPage(page.fileName);
        reply.type('text/html; charset=utf-8');
        return html;
      } catch (error) {
        logUnavailablePage(app, routePath, page.title, error);
        throw app.httpErrors.notFound(`${page.title} page is not available`);
      }
    });
  }

  app.get('/learn/review-queue', async (_request, reply) => {
    reply.type('text/html; charset=utf-8');
    return buildReviewQueuePage();
  });
}