export function buildLearnLandingPage(): string {
  return [
    '<!DOCTYPE html>',
    '<html lang="en">',
    '<head>',
    '  <meta charset="utf-8" />',
    '  <meta name="viewport" content="width=device-width, initial-scale=1" />',
    '  <title>Nexus Learn</title>',
    '  <style>',
    '    :root { color-scheme: light; --bg-top: #f8f2e5; --bg-bottom: #d9e6df; --ink: #18212b; --muted: rgba(24,33,43,0.72); --panel: rgba(255,255,255,0.82); --panel-strong: rgba(255,255,255,0.94); --line: rgba(24,33,43,0.1); --accent: #0c695b; --accent-soft: rgba(12,105,91,0.12); --shadow: 0 24px 64px rgba(24,33,43,0.1); --warn: #8b6208; }',
    '    * { box-sizing: border-box; }',
    '    body { margin: 0; font-family: "Avenir Next", "Segoe UI", sans-serif; color: var(--ink); background: radial-gradient(circle at top left, #fff9ef 0%, var(--bg-top) 44%, var(--bg-bottom) 100%); }',
    '    main { max-width: 1240px; margin: 0 auto; padding: 44px 20px 80px; }',
    '    h1 { margin: 0; font-size: clamp(2.8rem, 6vw, 5.2rem); line-height: 0.92; max-width: 10ch; }',
    '    h2 { margin: 0; font-size: clamp(1.6rem, 3vw, 2.4rem); }',
    '    p { color: var(--muted); line-height: 1.65; max-width: 74ch; }',
    '    a { color: inherit; }',
    '    .eyebrow { display: inline-flex; padding: 8px 10px; border-radius: 999px; background: var(--accent-soft); color: var(--accent); font: 700 0.76rem/1.1 ui-monospace, SFMono-Regular, Menlo, monospace; text-transform: uppercase; letter-spacing: 0.08em; }',
    '    .hero { display: grid; grid-template-columns: minmax(0, 1.3fr) minmax(280px, 0.9fr); gap: 20px; align-items: end; }',
    '    .hero-card, .card, .step, .reference-card, .progress-card, .control-panel { background: var(--panel); border: 1px solid var(--line); border-radius: 28px; box-shadow: var(--shadow); }',
    '    .hero-copy { display: grid; gap: 16px; }',
    '    .hero-card, .control-panel { padding: 22px; }',
    '    .hero-card ul { margin: 14px 0 0; padding-left: 18px; color: var(--muted); display: grid; gap: 10px; }',
    '    .actions, .row { display: flex; flex-wrap: wrap; gap: 10px; }',
    '    .button, .inline-button { display: inline-flex; align-items: center; justify-content: center; min-height: 46px; padding: 0 16px; border-radius: 14px; text-decoration: none; font-weight: 600; transition: transform 140ms ease, box-shadow 140ms ease; border: 1px solid transparent; cursor: pointer; font: inherit; }',
    '    .button:hover, .inline-button:hover { transform: translateY(-1px); }',
    '    .button-primary { background: var(--accent); color: #fffaf4; box-shadow: 0 12px 24px rgba(12,105,91,0.18); }',
    '    .button-secondary, .inline-button { background: var(--panel-strong); border-color: var(--line); color: var(--ink); }',
    '    .section { display: grid; gap: 18px; margin-top: 26px; }',
    '    .section-head { display: grid; gap: 10px; }',
    '    .section-row { display: flex; gap: 14px; align-items: center; justify-content: space-between; flex-wrap: wrap; }',
    '    .control-grid { display: grid; gap: 12px; grid-template-columns: repeat(4, minmax(0, 1fr)); }',
    '    label { display: grid; gap: 6px; color: var(--muted); font-size: 0.92rem; }',
    '    input, textarea, button { font: inherit; }',
    '    input, textarea { width: 100%; border: 1px solid var(--line); border-radius: 16px; background: rgba(255,255,255,0.78); padding: 12px; color: var(--ink); }',
    '    .status-bar { min-height: 46px; padding: 12px 14px; border-radius: 16px; border: 1px solid var(--line); background: rgba(255,255,255,0.7); color: var(--muted); }',
    '    .step-grid { display: grid; gap: 16px; grid-template-columns: repeat(5, minmax(0, 1fr)); }',
    '    .step { padding: 20px; display: grid; gap: 12px; }',
    '    .step-number { display: inline-flex; width: 34px; height: 34px; border-radius: 50%; align-items: center; justify-content: center; background: rgba(12,105,91,0.1); color: var(--accent); font: 700 0.9rem/1 ui-monospace, SFMono-Regular, Menlo, monospace; }',
    '    .step-links { display: grid; gap: 8px; }',
    '    .step-links a { text-decoration: none; color: var(--accent); font-weight: 600; }',
    '    .surface-grid { display: grid; gap: 16px; grid-template-columns: repeat(3, minmax(0, 1fr)); }',
    '    .card { padding: 22px; display: grid; gap: 12px; text-decoration: none; }',
    '    .card:hover { transform: translateY(-2px); }',
    '    .card-title { font-size: 1.3rem; }',
    '    .tag-row { display: flex; flex-wrap: wrap; gap: 8px; }',
    '    .tag { display: inline-flex; padding: 7px 10px; border-radius: 999px; background: rgba(12,105,91,0.1); color: var(--accent); font: 600 0.78rem/1 ui-monospace, SFMono-Regular, Menlo, monospace; }',
    '    .reference-grid { display: grid; gap: 16px; grid-template-columns: repeat(auto-fit, minmax(280px, 1fr)); }',
    '    .reference-card { padding: 22px; display: grid; gap: 10px; }',
    '    .progress-grid { display: grid; gap: 16px; grid-template-columns: repeat(3, minmax(0, 1fr)); }',
    '    .progress-card { padding: 20px; display: grid; gap: 10px; }',
    '    .progress-value { font-size: clamp(1.8rem, 4vw, 3rem); line-height: 0.95; }',
    '    .progress-note { color: var(--muted); }',
    '    .step-meta { display: flex; gap: 8px; align-items: center; justify-content: space-between; flex-wrap: wrap; }',
    '    .status-pill { display: inline-flex; padding: 7px 10px; border-radius: 999px; background: rgba(24,33,43,0.08); color: var(--ink); font: 600 0.78rem/1 ui-monospace, SFMono-Regular, Menlo, monospace; text-transform: uppercase; letter-spacing: 0.04em; }',
    '    .step-actions { display: flex; flex-wrap: wrap; gap: 8px; }',
    '    .state-button { border: 1px solid var(--line); background: var(--panel-strong); color: var(--ink); border-radius: 999px; min-height: 34px; padding: 0 12px; cursor: pointer; font: 600 0.82rem/1 ui-monospace, SFMono-Regular, Menlo, monospace; }',
    '    .state-button.is-active { background: var(--accent); border-color: var(--accent); color: #fffaf4; }',
    '    .state-button:disabled, .inline-button:disabled { opacity: 0.5; cursor: not-allowed; transform: none; }',
    '    .note-label { display: grid; gap: 8px; color: var(--muted); font-size: 0.92rem; }',
    '    .note-field { width: 100%; min-height: 96px; border-radius: 18px; border: 1px solid var(--line); background: rgba(255,255,255,0.74); padding: 12px; color: var(--ink); font: inherit; resize: vertical; }',
    '    .step.is-not-started { border-color: var(--line); }',
    '    .step.is-in-progress { border-color: rgba(181, 122, 17, 0.35); box-shadow: 0 24px 64px rgba(181, 122, 17, 0.12); }',
    '    .step.is-complete { border-color: rgba(12,105,91,0.35); box-shadow: 0 24px 64px rgba(12,105,91,0.14); }',
    '    .step.is-not-started .status-pill { background: rgba(24,33,43,0.08); }',
    '    .step.is-in-progress .status-pill { background: rgba(181, 122, 17, 0.14); color: #8b6208; }',
    '    .step.is-complete .status-pill { background: rgba(12,105,91,0.14); color: var(--accent); }',
    '    .storage-note { font-size: 0.88rem; color: var(--muted); }',
    '    .checklist { display: grid; gap: 12px; grid-template-columns: repeat(3, minmax(0, 1fr)); }',
    '    .check-item { background: rgba(255,255,255,0.62); border: 1px solid var(--line); border-radius: 18px; padding: 16px; }',
    '    .check-item strong { display: block; margin-bottom: 8px; }',
    '    .warn { color: var(--warn); }',
    '    @media (max-width: 1080px) { .hero, .step-grid, .surface-grid, .reference-grid, .progress-grid, .checklist, .control-grid { grid-template-columns: 1fr; } }',
    '  </style>',
    '</head>',
    '<body>',
    '  <main>',
    '    <section class="hero">',
    '      <div class="hero-copy">',
    '        <span class="eyebrow">Nexus Learn</span>',
    '        <h1>The guided runtime path for Pilot, Connect, Launch, Operate, and Promote.</h1>',
    '        <p>This page turns the runtime learn surfaces into one operator workflow. Start with the project boundary, connect GitHub and repository scope, launch intake safely, operate the queue, and only then promote work or durable customer access.</p>',
    '        <div class="actions">',
    '          <a class="button button-primary" href="/learn/onboarding">Start With Onboarding</a>',
    '          <a class="button button-secondary" href="/learn/review-queue">Open Review Queue</a>',
    '          <a class="button button-secondary" href="/learn/support-ops">Open Support Ops</a>',
    '        </div>',
    '      </div>',
    '      <aside class="hero-card">',
    '        <span class="eyebrow">Operator Rule</span>',
    '        <h2>Do not treat Nexus like a pile of tools.</h2>',
    '        <ul>',
    '          <li>Onboarding defines project and repository truth.</li>',
    '          <li>Review queue is the approval gate for downstream GitHub work.</li>',
    '          <li>Support Ops confirms live readiness before wider rollout or durable access.</li>',
    '        </ul>',
    '      </aside>',
    '    </section>',
    '    <section class="section">',
    '      <div class="section-head">',
    '        <span class="eyebrow">Shared Checklist</span>',
    '        <div class="section-row">',
    '          <h2>Keep the five-step rollout state in Nexus, scoped to a real project.</h2>',
    '          <button id="resetChecklist" class="inline-button" type="button">Reset Checklist</button>',
    '        </div>',
    '        <p class="storage-note">The rollout checklist persists per project inside Nexus. Only the connection fields on this page are kept in your browser.</p>',
    '      </div>',
    '      <div class="control-panel">',
    '        <div class="control-grid">',
    '          <label>Base URL<input id="baseUrl" value="" placeholder="http://127.0.0.1:4000" /></label>',
    '          <label>Bearer Token<input id="token" value="" placeholder="nexus-local-dev-token" /></label>',
    '          <label>Project Key<input id="projectKey" value="" placeholder="checkout-prod" /></label>',
    '          <label>Project Id<input id="projectId" value="" placeholder="project UUID optional" /></label>',
    '        </div>',
    '        <div class="row">',
    '          <button id="lookupProject" class="inline-button" type="button">Lookup Project</button>',
    '          <button id="loadChecklist" class="inline-button" type="button">Load Shared Checklist</button>',
    '        </div>',
    '        <div id="checklistStatus" class="status-bar">Connect a project and operator token to load the shared rollout checklist.</div>',
    '      </div>',
    '      <div class="progress-grid">',
    '        <article class="progress-card">',
    '          <span class="eyebrow">Completed</span>',
    '          <strong id="completedSteps" class="progress-value">0 / 5</strong>',
    '          <span class="progress-note">Steps marked complete for the connected project.</span>',
    '        </article>',
    '        <article class="progress-card">',
    '          <span class="eyebrow">Current Focus</span>',
    '          <strong id="currentFocus" class="progress-value">Connect Project</strong>',
    '          <span id="focusNote" class="progress-note">Load a project checklist before tracking rollout work.</span>',
    '        </article>',
    '        <article class="progress-card">',
    '          <span class="eyebrow">Last Update</span>',
    '          <strong id="lastUpdated" class="progress-value">Not loaded</strong>',
    '          <span class="progress-note">Updated whenever a checklist change is saved to Nexus.</span>',
    '        </article>',
    '      </div>',
    '    </section>',
    '    <section class="section">',
    '      <div class="section-head">',
    '        <span class="eyebrow">Five Steps</span>',
    '        <h2>Follow the journey in order.</h2>',
    '      </div>',
    '      <div class="step-grid">',
    '        <article class="step" data-step="pilot">',
    '          <span class="step-number">01</span>',
    '          <div class="step-meta"><span class="status-pill" data-step-status-label="pilot">Not started</span><span class="storage-note">Stored in Nexus for this project</span></div>',
    '          <strong>Pilot</strong>',
    '          <p>Create the workspace, define the project, and choose a narrow first rollout boundary.</p>',
    '          <div class="step-actions"><button class="state-button" type="button" data-step-target="pilot" data-step-status="not-started">Not started</button><button class="state-button" type="button" data-step-target="pilot" data-step-status="in-progress">In progress</button><button class="state-button" type="button" data-step-target="pilot" data-step-status="complete">Complete</button></div>',
    '          <label class="note-label">Operator note<textarea class="note-field" data-step-note="pilot" placeholder="Record the project key, rollout boundary, or unresolved setup work."></textarea></label>',
    '          <div class="step-links"><a href="/learn/onboarding">Use the onboarding console</a></div>',
    '        </article>',
    '        <article class="step" data-step="connect">',
    '          <span class="step-number">02</span>',
    '          <div class="step-meta"><span class="status-pill" data-step-status-label="connect">Not started</span><span class="storage-note">Stored in Nexus for this project</span></div>',
    '          <strong>Connect</strong>',
    '          <p>Attach GitHub auth, installation state, repository bindings, and service identities.</p>',
    '          <div class="step-actions"><button class="state-button" type="button" data-step-target="connect" data-step-status="not-started">Not started</button><button class="state-button" type="button" data-step-target="connect" data-step-status="in-progress">In progress</button><button class="state-button" type="button" data-step-target="connect" data-step-status="complete">Complete</button></div>',
    '          <label class="note-label">Operator note<textarea class="note-field" data-step-note="connect" placeholder="Record auth mode, install ids, repo bindings, or open access issues."></textarea></label>',
    '          <div class="step-links"><a href="/learn/onboarding">Manage install and repo scope</a></div>',
    '        </article>',
    '        <article class="step" data-step="launch">',
    '          <span class="step-number">03</span>',
    '          <div class="step-meta"><span class="status-pill" data-step-status-label="launch">Not started</span><span class="storage-note">Stored in Nexus for this project</span></div>',
    '          <strong>Launch</strong>',
    '          <p>Mint widget or embed sessions, validate support readiness, and confirm customer routes.</p>',
    '          <div class="step-actions"><button class="state-button" type="button" data-step-target="launch" data-step-status="not-started">Not started</button><button class="state-button" type="button" data-step-target="launch" data-step-status="in-progress">In progress</button><button class="state-button" type="button" data-step-target="launch" data-step-status="complete">Complete</button></div>',
    '          <label class="note-label">Operator note<textarea class="note-field" data-step-note="launch" placeholder="Record widget links, readiness blockers, or customer handoff details."></textarea></label>',
    '          <div class="step-links"><a href="/learn/onboarding">Mint launch handoff</a><a href="/learn/support-ops">Verify live readiness</a></div>',
    '        </article>',
    '        <article class="step" data-step="operate">',
    '          <span class="step-number">04</span>',
    '          <div class="step-meta"><span class="status-pill" data-step-status-label="operate">Not started</span><span class="storage-note">Stored in Nexus for this project</span></div>',
    '          <strong>Operate</strong>',
    '          <p>Run assignment, triage, and follow-up from the review queue and support surfaces.</p>',
    '          <div class="step-actions"><button class="state-button" type="button" data-step-target="operate" data-step-status="not-started">Not started</button><button class="state-button" type="button" data-step-target="operate" data-step-status="in-progress">In progress</button><button class="state-button" type="button" data-step-target="operate" data-step-status="complete">Complete</button></div>',
    '          <label class="note-label">Operator note<textarea class="note-field" data-step-note="operate" placeholder="Record queue owners, review rules, or live support follow-up."></textarea></label>',
    '          <div class="step-links"><a href="/learn/review-queue">Work the queue</a><a href="/learn/support-ops">Check support state</a></div>',
    '        </article>',
    '        <article class="step" data-step="promote">',
    '          <span class="step-number">05</span>',
    '          <div class="step-meta"><span class="status-pill" data-step-status-label="promote">Not started</span><span class="storage-note">Stored in Nexus for this project</span></div>',
    '          <strong>Promote</strong>',
    '          <p>Promote only approved, validation-safe work and only extend access when scope still holds.</p>',
    '          <div class="step-actions"><button class="state-button" type="button" data-step-target="promote" data-step-status="not-started">Not started</button><button class="state-button" type="button" data-step-target="promote" data-step-status="in-progress">In progress</button><button class="state-button" type="button" data-step-target="promote" data-step-status="complete">Complete</button></div>',
    '          <label class="note-label">Operator note<textarea class="note-field" data-step-note="promote" placeholder="Record promotion criteria, approvals, or reasons to hold back rollout."></textarea></label>',
    '          <div class="step-links"><a href="/learn/review-queue">Approve downstream action</a><a href="/learn/support-ops">Confirm promotion readiness</a></div>',
    '        </article>',
    '      </div>',
    '    </section>',
    '    <section class="section">',
    '      <div class="section-head">',
    '        <span class="eyebrow">Core Surfaces</span>',
    '        <h2>Use the runtime surfaces by stage, not by guesswork.</h2>',
    '      </div>',
    '      <div class="surface-grid">',
    '        <a class="card" href="/learn/onboarding">',
    '          <span class="card-title">Onboarding Console</span>',
    '          <div class="tag-row"><span class="tag">Pilot</span><span class="tag">Connect</span><span class="tag">Launch</span></div>',
    '          <p>Create the project, connect repository scope, reconcile GitHub installs, mint widget sessions, and manage service or portal setup.</p>',
    '        </a>',
    '        <a class="card" href="/learn/review-queue">',
    '          <span class="card-title">Review Queue</span>',
    '          <div class="tag-row"><span class="tag">Operate</span><span class="tag">Promote</span></div>',
    '          <p>Review hosted feedback, inspect context, assign ownership, and explicitly approve or reject downstream GitHub activity.</p>',
    '        </a>',
    '        <a class="card" href="/learn/support-ops">',
    '          <span class="card-title">Support Ops</span>',
    '          <div class="tag-row"><span class="tag">Launch</span><span class="tag">Operate</span><span class="tag">Promote</span></div>',
    '          <p>Verify readiness, inspect public route health, review recent hosted feedback, and confirm durable customer access stays in bounds.</p>',
    '        </a>',
    '      </div>',
    '    </section>',
    '    <section class="section">',
    '      <div class="section-head">',
    '        <span class="eyebrow">References</span>',
    '        <h2>Use the product story reference when you need context, not as a substitute for the workflow.</h2>',
    '      </div>',
    '      <div class="reference-grid">',
    '        <article class="reference-card">',
    '          <strong>Interactive PRD</strong>',
    '          <p>Use this for the product contract, system narrative, and roadmap context behind the operator flow.</p>',
    '          <a class="button button-secondary" href="/learn/prd">Open PRD</a>',
    '        </article>',
    '      </div>',
    '    </section>',
    '    <section class="section">',
    '      <div class="section-head">',
    '        <span class="eyebrow">Readiness Checks</span>',
    '        <h2>Before you move to the next step, confirm the current one is actually closed.</h2>',
    '      </div>',
    '      <div class="checklist">',
    '        <div class="check-item"><strong>Pilot is complete</strong><p>The project key is stable and the workspace boundary is clear.</p></div>',
    '        <div class="check-item"><strong>Connect is complete</strong><p>GitHub installation, repo connections, and auth mode are resolved.</p></div>',
    '        <div class="check-item"><strong>Launch is complete</strong><p>Widget, dashboard, portal, and support readiness all resolve cleanly.</p></div>',
    '      </div>',
    '    </section>',
    '  </main>',
    '  <script>',
    '    const connectionStorageKey = "nexus-learn-checklist-connection-v1";',
    '    const stepOrder = [',
    '      { id: "pilot", label: "Pilot", focus: "Define the workspace, project key, and rollout boundary." },',
    '      { id: "connect", label: "Connect", focus: "Resolve auth mode, installation state, and repository bindings." },',
    '      { id: "launch", label: "Launch", focus: "Validate intake routes, widget handoff, and readiness checks." },',
    '      { id: "operate", label: "Operate", focus: "Run the queue, assignments, and support follow-up from live surfaces." },',
    '      { id: "promote", label: "Promote", focus: "Only move reviewed, validation-safe work and access changes forward." }',
    '    ];',
    '    const statusLabels = { "not-started": "Not started", "in-progress": "In progress", complete: "Complete" };',
    '    const els = {',
    '      baseUrl: document.getElementById("baseUrl"),',
    '      token: document.getElementById("token"),',
    '      projectKey: document.getElementById("projectKey"),',
    '      projectId: document.getElementById("projectId"),',
    '      lookupProject: document.getElementById("lookupProject"),',
    '      loadChecklist: document.getElementById("loadChecklist"),',
    '      resetChecklist: document.getElementById("resetChecklist"),',
    '      checklistStatus: document.getElementById("checklistStatus"),',
    '      completedSteps: document.getElementById("completedSteps"),',
    '      currentFocus: document.getElementById("currentFocus"),',
    '      focusNote: document.getElementById("focusNote"),',
    '      lastUpdated: document.getElementById("lastUpdated")',
    '    };',
    '    const state = { loaded: false, projectId: "", projectKey: "", updatedAt: "", steps: createDefaultSteps() };',
    '    let saveTimer = null;',
    '    function createDefaultSteps() {',
    '      return Object.fromEntries(stepOrder.map((step) => [step.id, { status: "not-started", note: "" }]));',
    '    }',
    '    function createPayload() {',
    '      return { steps: { pilot: state.steps.pilot, connect: state.steps.connect, launch: state.steps.launch, operate: state.steps.operate, promote: state.steps.promote } };',
    '    }',
    '    function readSavedConnection() {',
    '      try { return JSON.parse(localStorage.getItem(connectionStorageKey) || "{}"); } catch { return {}; }',
    '    }',
    '    function saveConnection() {',
    '      localStorage.setItem(connectionStorageKey, JSON.stringify({ baseUrl: els.baseUrl.value.trim(), token: els.token.value.trim(), projectKey: els.projectKey.value.trim(), projectId: els.projectId.value.trim() }));',
    '    }',
    '    function setStatus(message, isWarning) {',
    '      els.checklistStatus.textContent = message;',
    '      els.checklistStatus.className = "status-bar" + (isWarning ? " warn" : "");',
    '    }',
    '    function authHeaders() {',
    '      const token = els.token.value.trim();',
    '      return token ? { Authorization: "Bearer " + token } : {};',
    '    }',
    '    async function request(path, init) {',
    '      const response = await fetch((els.baseUrl.value.trim() || window.location.origin) + path, init);',
    '      const text = await response.text();',
    '      if (!response.ok) { throw new Error((init && init.method ? init.method : "GET") + " " + path + " failed: " + response.status + " " + text); }',
    '      return JSON.parse(text);',
    '    }',
    '    function formatUpdatedAt(value) {',
    '      if (!value) return state.loaded ? "Not saved yet" : "Not loaded";',
    '      const date = new Date(value);',
    '      if (Number.isNaN(date.getTime())) return state.loaded ? "Not saved yet" : "Not loaded";',
    '      return date.toLocaleString();',
    '    }',
    '    function describeCurrentFocus() {',
    '      if (!state.loaded) return null;',
    '      const inProgress = stepOrder.find((step) => state.steps[step.id].status === "in-progress");',
    '      if (inProgress) return inProgress;',
    '      const nextStep = stepOrder.find((step) => state.steps[step.id].status !== "complete");',
    '      return nextStep || null;',
    '    }',
    '    function setInteractiveEnabled(enabled) {',
    '      document.querySelectorAll("[data-step-status]").forEach((button) => { button.disabled = !enabled; });',
    '      document.querySelectorAll("[data-step-note]").forEach((field) => { field.disabled = !enabled; });',
    '      els.resetChecklist.disabled = !enabled;',
    '    }',
    '    function render() {',
    '      const completedCount = stepOrder.filter((step) => state.steps[step.id].status === "complete").length;',
    '      const currentFocus = describeCurrentFocus();',
    '      els.completedSteps.textContent = completedCount + " / " + stepOrder.length;',
    '      els.currentFocus.textContent = state.loaded ? (currentFocus ? currentFocus.label : "Rollout complete") : "Connect Project";',
    '      els.focusNote.textContent = state.loaded ? (currentFocus ? currentFocus.focus : "All five steps are complete for the connected project.") : "Load a project checklist before tracking rollout work.";',
    '      els.lastUpdated.textContent = formatUpdatedAt(state.updatedAt);',
    '      for (const step of stepOrder) {',
    '        const stepState = state.steps[step.id];',
    "        const article = document.querySelector('[data-step=\"' + step.id + '\"]');",
    "        const statusLabel = document.querySelector('[data-step-status-label=\"' + step.id + '\"]');",
    "        const noteField = document.querySelector('[data-step-note=\"' + step.id + '\"]');",
    '        if (article) { article.classList.remove("is-not-started", "is-in-progress", "is-complete"); article.classList.add("is-" + stepState.status); }',
    '        if (statusLabel) statusLabel.textContent = statusLabels[stepState.status] || statusLabels["not-started"];',
    '        if (noteField && noteField.value !== stepState.note) noteField.value = stepState.note;',
    "        document.querySelectorAll('[data-step-target=\"' + step.id + '\"]').forEach((button) => { button.classList.toggle('is-active', button.getAttribute('data-step-status') === stepState.status); });",
    '      }',
    '      setInteractiveEnabled(state.loaded);',
    '    }',
    '    async function lookupProject() {',
    '      saveConnection();',
    '      const projectKey = els.projectKey.value.trim();',
    '      if (!projectKey) { setStatus("Project Key is required for lookup.", true); return; }',
    '      setStatus("Looking up project " + projectKey + "...");',
    '      try {',
    '        const result = await request("/internal/projects/key/" + encodeURIComponent(projectKey), { headers: authHeaders() });',
    '        els.projectId.value = result.project && result.project.id ? result.project.id : "";',
    '        els.projectKey.value = result.project && result.project.projectKey ? result.project.projectKey : projectKey;',
    '        saveConnection();',
    '        setStatus("Project lookup loaded for " + els.projectKey.value + ".");',
    '      } catch (error) {',
    '        setStatus(error instanceof Error ? error.message : "Failed to look up project.", true);',
    '      }',
    '    }',
    '    async function loadChecklist() {',
    '      saveConnection();',
    '      let projectId = els.projectId.value.trim();',
    '      if (!projectId && els.projectKey.value.trim()) {',
    '        await lookupProject();',
    '        projectId = els.projectId.value.trim();',
    '      }',
    '      if (!projectId) { setStatus("Project Id or Project Key is required to load the shared checklist.", true); return; }',
    '      setStatus("Loading shared checklist for " + projectId + "...");',
    '      try {',
    '        const result = await request("/internal/projects/" + projectId + "/rollout-checklist", { headers: authHeaders() });',
    '        state.loaded = true;',
    '        state.projectId = result.project && result.project.id ? result.project.id : projectId;',
    '        state.projectKey = result.project && result.project.projectKey ? result.project.projectKey : els.projectKey.value.trim();',
    '        state.steps = result.checklist && result.checklist.steps ? result.checklist.steps : createDefaultSteps();',
    '        state.updatedAt = result.checklist && result.checklist.updatedAt ? result.checklist.updatedAt : "";',
    '        render();',
    '        setStatus("Shared checklist loaded for " + (state.projectKey || state.projectId) + ".");',
    '      } catch (error) {',
    '        state.loaded = false;',
    '        state.steps = createDefaultSteps();',
    '        state.updatedAt = "";',
    '        render();',
    '        setStatus(error instanceof Error ? error.message : "Failed to load shared checklist.", true);',
    '      }',
    '    }',
    '    async function persistChecklist(reason) {',
    '      if (!state.loaded || !state.projectId) return;',
    '      try {',
    '        const result = await request("/internal/projects/" + state.projectId + "/rollout-checklist", { method: "PUT", headers: Object.assign({ "content-type": "application/json" }, authHeaders()), body: JSON.stringify(createPayload()) });',
    '        state.updatedAt = result.checklist && result.checklist.updatedAt ? result.checklist.updatedAt : state.updatedAt;',
    '        render();',
    '        setStatus(reason + " saved for " + (state.projectKey || state.projectId) + ".");',
    '      } catch (error) {',
    '        setStatus(error instanceof Error ? error.message : "Failed to save shared checklist.", true);',
    '      }',
    '    }',
    '    function schedulePersist(reason) {',
    '      if (!state.loaded) return;',
    '      if (saveTimer) window.clearTimeout(saveTimer);',
    '      setStatus("Saving " + reason.toLowerCase() + " for " + (state.projectKey || state.projectId) + "...");',
    '      saveTimer = window.setTimeout(function () { persistChecklist(reason); }, 250);',
    '    }',
    '    document.querySelectorAll("[data-step-status]").forEach((button) => {',
    '      button.addEventListener("click", function () {',
    '        if (!state.loaded) { setStatus("Load a shared checklist before editing rollout state.", true); return; }',
    '        const stepId = button.getAttribute("data-step-target");',
    '        const status = button.getAttribute("data-step-status");',
    '        if (!stepId || !state.steps[stepId]) return;',
    '        state.steps[stepId].status = status === "complete" || status === "in-progress" ? status : "not-started";',
    '        render();',
    '        schedulePersist(statusLabels[state.steps[stepId].status] + " state");',
    '      });',
    '    });',
    '    document.querySelectorAll("[data-step-note]").forEach((field) => {',
    '      field.addEventListener("input", function () {',
    '        if (!state.loaded) { setStatus("Load a shared checklist before editing rollout notes.", true); return; }',
    '        const stepId = field.getAttribute("data-step-note");',
    '        if (!stepId || !state.steps[stepId]) return;',
    '        state.steps[stepId].note = field.value;',
    '        render();',
    '        schedulePersist("Checklist notes");',
    '      });',
    '    });',
    '    els.lookupProject.addEventListener("click", lookupProject);',
    '    els.loadChecklist.addEventListener("click", loadChecklist);',
    '    els.resetChecklist.addEventListener("click", async function () {',
    '      if (!state.loaded) { setStatus("Load a shared checklist before resetting it.", true); return; }',
    '      state.steps = createDefaultSteps();',
    '      render();',
    '      await persistChecklist("Checklist reset");',
    '    });',
    '    const saved = readSavedConnection();',
    '    const params = new URLSearchParams(window.location.search);',
    '    els.baseUrl.value = saved.baseUrl || window.location.origin;',
    '    els.token.value = saved.token || "";',
    '    els.projectKey.value = params.get("projectKey") || saved.projectKey || "";',
    '    els.projectId.value = params.get("projectId") || saved.projectId || "";',
    '    render();',
    '    if ((els.projectId.value || els.projectKey.value) && els.token.value.trim()) { loadChecklist().catch(function () { return undefined; }); }',
    '  </script>',
    '</body>',
    '</html>'
  ].join('\n');
}