export function buildReviewQueuePage(): string {
  return [
    '<!DOCTYPE html>',
    '<html lang="en">',
    '<head>',
    '  <meta charset="utf-8" />',
    '  <meta name="viewport" content="width=device-width, initial-scale=1" />',
    '  <title>Nexus Review Queue</title>',
    '  <style>',
    '    :root { color-scheme: light; --bg-top: #f8f1dd; --bg-bottom: #d7e2db; --ink: #18212b; --muted: rgba(24,33,43,0.68); --panel: rgba(255,255,255,0.84); --panel-strong: rgba(255,255,255,0.94); --line: rgba(24,33,43,0.12); --accent: #0d5e55; --accent-soft: rgba(13,94,85,0.12); --accent-ink: #0a3d37; --good: #0f6b46; --bad: #922f2f; --warn: #8b6208; --shadow: 0 22px 56px rgba(24,33,43,0.12); }',
    '    * { box-sizing: border-box; }',
    '    body { margin: 0; font-family: "Iowan Old Style", Georgia, serif; color: var(--ink); background: radial-gradient(circle at top left, #fff8eb 0%, var(--bg-top) 36%, var(--bg-bottom) 100%); }',
    '    main { max-width: 1340px; margin: 0 auto; padding: 36px 18px 60px; }',
    '    h1 { margin: 0 0 10px; font-size: clamp(2.7rem, 5vw, 5rem); line-height: 0.92; max-width: 12ch; }',
    '    p { color: var(--muted); max-width: 76ch; line-height: 1.6; }',
    '    .eyebrow { display: inline-block; margin-bottom: 14px; padding: 8px 10px; border-radius: 999px; background: var(--accent-soft); color: var(--accent); font: 600 0.76rem/1.1 ui-monospace, SFMono-Regular, Menlo, monospace; text-transform: uppercase; letter-spacing: 0.08em; }',
    '    .hero { display: grid; gap: 20px; }',
    '    .hero-grid { display: grid; grid-template-columns: minmax(0, 1.5fr) minmax(280px, 0.9fr); gap: 18px; align-items: end; }',
    '    .summary-grid { display: grid; grid-template-columns: repeat(4, minmax(0, 1fr)); gap: 14px; }',
    '    .summary-card { background: linear-gradient(180deg, rgba(255,255,255,0.95), rgba(255,255,255,0.76)); border: 1px solid rgba(255,255,255,0.5); border-radius: 24px; padding: 18px; box-shadow: var(--shadow); min-height: 120px; }',
    '    .summary-label { display: block; color: var(--muted); font: 600 0.78rem/1.2 ui-monospace, SFMono-Regular, Menlo, monospace; text-transform: uppercase; letter-spacing: 0.08em; }',
    '    .summary-value { display: block; margin-top: 10px; font-size: clamp(1.8rem, 4vw, 3rem); line-height: 0.95; }',
    '    .summary-note { margin-top: 10px; font-size: 0.95rem; color: var(--muted); }',
    '    .shell { display: grid; grid-template-columns: 390px minmax(0, 1fr); gap: 18px; margin-top: 28px; }',
    '    .panel { background: var(--panel); border: 1px solid var(--line); border-radius: 28px; box-shadow: var(--shadow); overflow: hidden; backdrop-filter: blur(10px); }',
    '    .controls { padding: 18px; display: grid; gap: 12px; }',
    '    label { display: grid; gap: 6px; font-size: 0.92rem; color: var(--muted); }',
    '    input, textarea, button, select { font: inherit; }',
    '    input, textarea, select { width: 100%; border: 1px solid var(--line); border-radius: 14px; padding: 11px 12px; background: var(--panel-strong); color: var(--ink); }',
    '    textarea { min-height: 96px; resize: vertical; }',
    '    button { border: none; border-radius: 14px; padding: 12px 14px; cursor: pointer; transition: transform 140ms ease, opacity 140ms ease; }',
    '    button:hover { transform: translateY(-1px); }',
    '    button.primary { background: var(--accent); color: #fffaf6; }',
    '    button.secondary { background: rgba(255,255,255,0.86); border: 1px solid var(--line); color: var(--ink); }',
    '    button.success { background: var(--good); color: white; }',
    '    button.danger { background: var(--bad); color: white; }',
    '    button:disabled { opacity: 0.5; cursor: not-allowed; transform: none; }',
    '    .list { display: grid; gap: 10px; padding: 0 18px 18px; max-height: 640px; overflow: auto; }',
    '    .item { width: 100%; text-align: left; border: 1px solid var(--line); border-radius: 20px; padding: 14px; background: rgba(255,255,255,0.72); cursor: pointer; }',
    '    .item.active { border-color: rgba(13,94,85,0.45); box-shadow: inset 0 0 0 1px rgba(13,94,85,0.2); background: rgba(239,249,246,0.96); }',
    '    .item-header { display: flex; gap: 10px; align-items: flex-start; }',
    '    .item-check { margin-top: 2px; width: 18px; height: 18px; accent-color: var(--accent); }',
    '    .item h3 { margin: 0 0 8px; font-size: 1.04rem; }',
    '    .meta { display: flex; flex-wrap: wrap; gap: 8px; font-size: 0.8rem; color: var(--muted); }',
    '    .badge { display: inline-flex; align-items: center; gap: 6px; border-radius: 999px; padding: 6px 9px; background: #eef4f2; }',
    '    .stack { display: grid; gap: 14px; }',
    '    .summary-strip { display: grid; gap: 10px; grid-template-columns: repeat(auto-fit, minmax(180px, 1fr)); }',
    '    .mini-card { border: 1px solid var(--line); border-radius: 18px; padding: 14px; background: rgba(255,255,255,0.78); }',
    '    .bulk-box { display: grid; gap: 10px; }',
    '    .project-pills { display: flex; flex-wrap: wrap; gap: 10px; }',
    '    .project-pill { border: 1px solid var(--line); background: rgba(255,255,255,0.72); color: var(--ink); padding: 10px 12px; border-radius: 16px; text-align: left; }',
    '    .project-pill.active { background: rgba(13,94,85,0.14); border-color: rgba(13,94,85,0.35); color: var(--accent-ink); }',
    '    .workspace { padding: 18px; display: grid; gap: 16px; min-height: 760px; }',
    '    .workspace pre { margin: 0; padding: 14px; border-radius: 16px; background: #231f20; color: #f7efe3; overflow: auto; font: 0.82rem/1.45 ui-monospace, SFMono-Regular, Menlo, monospace; }',
    '    .empty { display: grid; place-items: center; min-height: 280px; color: var(--muted); border: 1px dashed var(--line); border-radius: 18px; }',
    '    .split { display: grid; grid-template-columns: repeat(2, minmax(0, 1fr)); gap: 14px; }',
    '    .status { padding: 12px 14px; border-top: 1px solid var(--line); background: rgba(31,36,48,0.03); color: var(--muted); min-height: 48px; }',
    '    .row { display: flex; gap: 10px; flex-wrap: wrap; }',
    '    .row.spread { justify-content: space-between; align-items: center; }',
    '    .section-title { margin: 0; font-size: 0.9rem; letter-spacing: 0.04em; text-transform: uppercase; color: var(--muted); }',
    '    .helper { font-size: 0.85rem; color: var(--muted); }',
    '    .timeline { display: grid; gap: 10px; }',
    '    .timeline-entry { border: 1px solid var(--line); border-radius: 16px; padding: 12px; background: rgba(255,255,255,0.78); }',
    '    .timeline-entry strong { display: block; margin-bottom: 4px; }',
    '    .pager { display: flex; gap: 10px; align-items: center; justify-content: space-between; padding: 0 18px 18px; }',
    '    .pager-group { display: flex; gap: 10px; align-items: center; }',
    '    .guardrail-grid { display: grid; gap: 10px; grid-template-columns: repeat(4, minmax(0, 1fr)); }',
    '    .guardrail-card { border: 1px solid var(--line); border-radius: 18px; padding: 14px; background: rgba(255,255,255,0.78); }',
    '    .guardrail-card strong { display: block; font-size: 0.94rem; }',
    '    .guardrail-card span { display: block; margin-top: 8px; color: var(--muted); font-size: 0.84rem; line-height: 1.45; }',
    '    .guardrail-pass { border-color: rgba(13,94,85,0.28); background: rgba(13,94,85,0.08); }',
    '    .guardrail-pass strong { color: var(--accent); }',
    '    .guardrail-fail { border-color: rgba(139,98,8,0.26); background: rgba(139,98,8,0.09); }',
    '    .guardrail-fail strong { color: var(--warn); }',
    '    .guardrail-neutral { border-color: var(--line); }',
    '    @media (max-width: 1120px) { .hero-grid, .shell, .split { grid-template-columns: 1fr; } .summary-grid { grid-template-columns: repeat(2, minmax(0, 1fr)); } }',
    '    @media (max-width: 680px) { .summary-grid { grid-template-columns: 1fr; } main { padding-inline: 12px; } }',
    '  </style>',
    '</head>',
    '<body>',
    '  <main>',
    '    <section class="hero">',
    '      <span class="eyebrow">Review • Decide</span>',
    '      <div class="hero-grid">',
    '        <div>',
    '          <h1>Review reports before anything moves into GitHub.</h1>',
    '          <p>This queue should help an operator make the next decision quickly. Load the report, inspect the evidence, and approve or reject the downstream action only when the target, context, and notes are clear.</p>',
    '        </div>',
    '        <div class="summary-grid">',
    '          <article class="summary-card"><span class="summary-label">Reports Waiting</span><span id="queuedCount" class="summary-value">0</span><span class="summary-note" id="queuedNote">Reports visible in the current filter.</span></article>',
    '          <article class="summary-card"><span class="summary-label">Needs Attention</span><span id="criticalCount" class="summary-value">0</span><span class="summary-note">Critical reports still waiting on review.</span></article>',
    '          <article class="summary-card"><span class="summary-label">Projects</span><span id="projectCount" class="summary-value">0</span><span class="summary-note">Projects represented in this review slice.</span></article>',
    '          <article class="summary-card"><span class="summary-label">Page</span><span id="pageValue" class="summary-value">1</span><span class="summary-note" id="pageNote">Current page and sort state.</span></article>',
    '        </div>',
    '      </div>',
    '    </section>',
    '    <section class="shell">',
    '      <aside class="panel">',
    '        <div class="controls">',
    '          <label>Base URL<input id="baseUrl" value="" placeholder="http://127.0.0.1:4000" /></label>',
    '          <label>Bearer Token (optional)<input id="token" value="" placeholder="nexus-local-dev-token" /></label>',
    '          <label>Project Id Filter<input id="projectId" value="" placeholder="Optional project UUID" /></label>',
    '          <label>Assigned To<input id="assignedTo" value="" placeholder="Filter by reviewer or operator id" /></label>',
    '          <label>Search Reports<input id="search" value="" placeholder="Project, repo, title, reporter" /></label>',
    '          <label>Sort By<select id="sort"><option value="newest">Newest first</option><option value="oldest">Oldest first</option><option value="impact">Highest impact</option><option value="severity">Highest severity</option></select></label>',
    '          <div class="row">',
    '            <button id="refresh" class="primary">Load Reports</button>',
    '            <button id="clearToken" class="secondary">Clear Saved Auth</button>',
    '          </div>',
    '          <div class="stack">',
    '            <h2 class="section-title">Project Queues</h2>',
    '            <div id="projectSummaries" class="project-pills"></div>',
    '          </div>',
    '          <div class="bulk-box">',
    '            <h2 class="section-title">Batch Decisions</h2>',
    '            <label>Assign Selected To<input id="bulkReviewerId" value="" placeholder="defaults to your operator id" /></label>',
    '            <label>Bulk Repository Override<input id="bulkRepository" value="" placeholder="owner/repo optional" /></label>',
    '            <label>Bulk Notes<textarea id="bulkNotes" placeholder="Applied to selected queued reports."></textarea></label>',
    '            <div class="row">',
    '              <button id="assignSelected" class="secondary">Assign</button>',
    '              <button id="approveSelected" class="success">Approve</button>',
    '              <button id="rejectSelected" class="danger">Reject</button>',
    '              <button id="clearSelection" class="secondary">Clear</button>',
    '            </div>',
    '          </div>',
    '        </div>',
    '        <div id="queue" class="list"></div>',
    '        <div class="pager">',
    '          <div class="pager-group">',
    '            <button id="previousPage" class="secondary">Previous</button>',
    '            <button id="nextPage" class="secondary">Next</button>',
    '          </div>',
    '          <div class="helper" id="pageSummary">Page 1</div>',
    '        </div>',
    '        <div id="queueStatus" class="status">Queue not loaded yet.</div>',
    '      </aside>',
    '      <section class="panel workspace">',
    '        <div class="summary-strip">',
    '          <article class="mini-card"><h2 class="section-title">Queue Mix</h2><div id="severitySummary" class="helper">No queue data loaded yet.</div></article>',
    '          <article class="mini-card"><h2 class="section-title">Filter State</h2><div id="filterSummary" class="helper">No filters applied.</div></article>',
    '          <article class="mini-card"><h2 class="section-title">Queue Window</h2><div id="windowSummary" class="helper">Waiting for queue data.</div></article>',
    '          <article class="mini-card"><h2 class="section-title">Approval Health</h2><div id="workflowSummary" class="helper">No queue data loaded yet.</div></article>',
    '        </div>',
    '        <div>',
    '          <h2 class="section-title">Approval Checklist</h2>',
    '          <div class="guardrail-grid">',
    '            <article id="guardrailTarget" class="guardrail-card guardrail-neutral"><strong>No report selected</strong><span>Select a report before making an approval decision.</span></article>',
    '            <article id="guardrailContext" class="guardrail-card guardrail-neutral"><strong>Evidence not loaded</strong><span>Load the report context before acting.</span></article>',
    '            <article id="guardrailRationale" class="guardrail-card guardrail-neutral"><strong>Decision notes missing</strong><span>Add notes so the approval or rejection has clear operator reasoning.</span></article>',
    '            <article id="guardrailPromotion" class="guardrail-card guardrail-neutral"><strong>Approval is blocked</strong><span>Approval stays blocked until target, evidence, and notes are all visible.</span></article>',
    '          </div>',
    '        </div>',
    '        <div class="split">',
    '          <div>',
    '            <h2 class="section-title">Selected Report</h2>',
    '            <div id="summary" class="empty">Select a report to inspect its details.</div>',
    '          </div>',
    '          <div>',
    '            <h2 class="section-title">Review Decision</h2>',
    '            <label>Repository Override<input id="repository" value="" placeholder="owner/repo optional" /></label>',
    '            <label>Notes<textarea id="notes" placeholder="Record why this was approved or rejected."></textarea></label>',
    '            <div class="row">',
    '              <button id="approve" class="success" disabled>Approve</button>',
    '              <button id="reject" class="danger" disabled>Reject</button>',
    '            </div>',
    '          </div>',
    '        </div>',
    '        <div>',
    '          <h2 class="section-title">Evidence</h2>',
    '          <pre id="context">// report evidence appears here</pre>',
    '        </div>',
    '        <div>',
    '          <h2 class="section-title">Review History</h2>',
    '          <div id="reviewActivity" class="timeline"><div class="empty">Select a report to inspect its review history.</div></div>',
    '        </div>',
    '      </section>',
    '    </section>',
    '  </main>',
    '  <script>',
    '    const storageKey = "nexus-review-queue-auth";',
    '    const state = { items: [], selected: null, selectedIds: [], context: null, summary: null, filters: { page: 1, limit: 12, sort: "newest", projectId: "", assignedTo: "", search: "" } };',
    '    const els = {',
    '      baseUrl: document.getElementById("baseUrl"),',
    '      token: document.getElementById("token"),',
    '      projectId: document.getElementById("projectId"),',
    '      assignedTo: document.getElementById("assignedTo"),',
    '      search: document.getElementById("search"),',
    '      sort: document.getElementById("sort"),',
    '      refresh: document.getElementById("refresh"),',
    '      clearToken: document.getElementById("clearToken"),',
    '      previousPage: document.getElementById("previousPage"),',
    '      nextPage: document.getElementById("nextPage"),',
    '      queue: document.getElementById("queue"),',
    '      queueStatus: document.getElementById("queueStatus"),',
    '      bulkReviewerId: document.getElementById("bulkReviewerId"),',
    '      bulkRepository: document.getElementById("bulkRepository"),',
    '      bulkNotes: document.getElementById("bulkNotes"),',
    '      assignSelected: document.getElementById("assignSelected"),',
    '      approveSelected: document.getElementById("approveSelected"),',
    '      rejectSelected: document.getElementById("rejectSelected"),',
    '      clearSelection: document.getElementById("clearSelection"),',
    '      projectSummaries: document.getElementById("projectSummaries"),',
    '      pageSummary: document.getElementById("pageSummary"),',
    '      queuedCount: document.getElementById("queuedCount"),',
    '      queuedNote: document.getElementById("queuedNote"),',
    '      criticalCount: document.getElementById("criticalCount"),',
    '      projectCount: document.getElementById("projectCount"),',
    '      pageValue: document.getElementById("pageValue"),',
    '      pageNote: document.getElementById("pageNote"),',
    '      severitySummary: document.getElementById("severitySummary"),',
    '      filterSummary: document.getElementById("filterSummary"),',
    '      windowSummary: document.getElementById("windowSummary"),',
    '      workflowSummary: document.getElementById("workflowSummary"),',
    '      summary: document.getElementById("summary"),',
    '      repository: document.getElementById("repository"),',
    '      notes: document.getElementById("notes"),',
    '      approve: document.getElementById("approve"),',
    '      reject: document.getElementById("reject"),',
    '      context: document.getElementById("context"),',
    '      reviewActivity: document.getElementById("reviewActivity"),',
    '      guardrailTarget: document.getElementById("guardrailTarget"),',
    '      guardrailContext: document.getElementById("guardrailContext"),',
    '      guardrailRationale: document.getElementById("guardrailRationale"),',
    '      guardrailPromotion: document.getElementById("guardrailPromotion")',
    '    };',
    '    function readSaved() {',
    '      try { return JSON.parse(localStorage.getItem(storageKey) || "{}"); } catch { return {}; }',
    '    }',
    '    function saveAuth() {',
    '      localStorage.setItem(storageKey, JSON.stringify({ baseUrl: els.baseUrl.value.trim(), token: els.token.value.trim(), projectId: els.projectId.value.trim(), assignedTo: els.assignedTo.value.trim(), search: els.search.value.trim(), sort: els.sort.value }));',
    '    }',
    '    function setStatus(message) { els.queueStatus.textContent = message; }',
    '    function authHeaders() {',
    '      const token = els.token.value.trim();',
    '      return token ? { Authorization: `Bearer ${token}` } : {};',
    '    }',
    '    function escapeHtml(value) {',
    '      return String(value ?? "").replace(/[&<>"\']/g, (character) => {',
    '        if (character === "&") return "&amp;";',
    '        if (character === "<") return "&lt;";',
    '        if (character === ">") return "&gt;";',
    '        if (character.charCodeAt(0) === 34) return "&quot;";',
    '        if (character.charCodeAt(0) === 39) return "&#39;";',
    '        return character;',
    '      });',
    '    }',
    '    function relativeTime(value) {',
    '      if (!value) return "unknown";',
    '      const milliseconds = Date.now() - new Date(value).getTime();',
    '      const minutes = Math.round(milliseconds / 60000);',
    '      if (!Number.isFinite(minutes)) return "unknown";',
    '      if (Math.abs(minutes) < 60) return `${minutes}m ago`;',
    '      const hours = Math.round(minutes / 60);',
    '      if (Math.abs(hours) < 48) return `${hours}h ago`;',
    '      const days = Math.round(hours / 24);',
    '      return `${days}d ago`;',
    '    }',
    '    function isSelected(reportId) { return state.selectedIds.includes(reportId); }',
    '    function clearSelection() { state.selectedIds = []; renderQueue(); renderSummary(); }',
    '    function toggleSelection(reportId) {',
    '      state.selectedIds = isSelected(reportId) ? state.selectedIds.filter((id) => id !== reportId) : [...state.selectedIds, reportId];',
    '      renderQueue();',
    '      renderSummary();',
    '    }',
    '    async function request(path, init) {',
    '      const baseUrl = els.baseUrl.value.trim() || window.location.origin;',
    '      const response = await fetch(baseUrl + path, init);',
    '      const text = await response.text();',
    '      if (!response.ok) { throw new Error(`${init && init.method ? init.method : "GET"} ${path} failed: ${response.status} ${text}`); }',
    '      return JSON.parse(text);',
    '    }',
    '    function renderGuardrailCard(target, tone, title, detail) {',
    '      target.className = `guardrail-card guardrail-${tone}`;',
    '      target.innerHTML = `<strong>${escapeHtml(title)}</strong><span>${escapeHtml(detail)}</span>`;',
    '    }',
    '    function canRejectSelection() {',
    '      return Boolean(state.selected && els.notes.value.trim());',
    '    }',
    '    function canApproveSelection() {',
    '      const repositoryTarget = els.repository.value.trim() || (state.selected && state.selected.repository) || "";',
    '      return Boolean(state.selected && state.context && els.notes.value.trim() && repositoryTarget);',
    '    }',
    '    function renderGuardrails() {',
    '      const repositoryTarget = els.repository.value.trim() || (state.selected && state.selected.repository) || "";',
    '      renderGuardrailCard(els.guardrailTarget, state.selected && repositoryTarget ? "pass" : state.selected ? "fail" : "neutral", state.selected && repositoryTarget ? "Repository target is ready" : state.selected ? "Repository target is missing" : "No report selected", state.selected && repositoryTarget ? `This review will target ${repositoryTarget}.` : state.selected ? "Choose the repository target before approving downstream GitHub work." : "Pick a report before you decide anything.");',
    '      renderGuardrailCard(els.guardrailContext, state.context ? "pass" : state.selected ? "fail" : "neutral", state.context ? "Evidence is loaded" : state.selected ? "Evidence is still loading" : "Evidence not loaded", state.context ? "Evidence and review history are visible for this report." : state.selected ? "Wait for the evidence load before approving or rejecting this report." : "Select a report to inspect evidence.");',
    '      renderGuardrailCard(els.guardrailRationale, els.notes.value.trim() ? "pass" : state.selected ? "fail" : "neutral", els.notes.value.trim() ? "Decision notes are ready" : state.selected ? "Decision notes are missing" : "No notes needed yet", els.notes.value.trim() ? "Operator notes are present for the next action." : state.selected ? "Add notes before approving or rejecting the selected report." : "Notes become required once a report is selected.");',
    '      renderGuardrailCard(els.guardrailPromotion, canApproveSelection() ? "pass" : state.selected ? "fail" : "neutral", canApproveSelection() ? "Approval is unblocked" : state.selected ? "Approval is still blocked" : "Approval is idle", canApproveSelection() ? "Approval can proceed because target, evidence, and notes are all visible." : state.selected ? "Approval stays blocked until repository target, evidence, and notes are all present." : "Choose a report before acting.");',
    '      els.approve.disabled = !canApproveSelection();',
    '      els.reject.disabled = !canRejectSelection();',
    '    }',
    '    function renderSummary() {',
    '      const summary = state.summary;',
    '      const filters = state.filters;',
    '      const severityCounts = summary && summary.severityCounts ? summary.severityCounts : {};',
    '      const workflow = summary && summary.workflow ? summary.workflow : null;',
    '      const projectSummaries = summary && Array.isArray(summary.projectSummaries) ? summary.projectSummaries : [];',
    '      els.queuedCount.textContent = String(summary ? summary.totalItems : 0);',
    '      els.criticalCount.textContent = String(severityCounts.critical || 0);',
    '      els.projectCount.textContent = String(projectSummaries.length);',
    '      els.pageValue.textContent = String(filters.page);',
    '      els.pageNote.textContent = `${filters.sort} order | ${state.selectedIds.length} selected`;',
    '      els.queuedNote.textContent = summary ? `${summary.totalPages} page${summary.totalPages === 1 ? "" : "s"} in current queue filter.` : "Pending reports across the current filter.";',
    '      const severityText = Object.entries(severityCounts).length ? Object.entries(severityCounts).map(([key, value]) => `${key}: ${value}`).join(" | ") : "No queue data loaded yet.";',
    '      els.severitySummary.textContent = severityText;',
    '      const activeFilters = [filters.projectId ? `project ${filters.projectId}` : null, filters.assignedTo ? `assigned ${filters.assignedTo}` : null, filters.search ? `search \"${filters.search}\"` : null].filter(Boolean).join(" | ") || "No filters applied.";',
    '      els.filterSummary.textContent = activeFilters;',
    '      els.windowSummary.textContent = summary ? `${state.items.length} item${state.items.length === 1 ? "" : "s"} shown on page ${filters.page} of ${summary.totalPages}.` : "Waiting for queue data.";',
    '      els.workflowSummary.textContent = workflow ? `assigned ${workflow.assignedCount} | unassigned ${workflow.unassignedCount} | stale ${workflow.staleCount} | oldest ${workflow.oldestPendingAgeHours}h | avg ${workflow.averageAgeHours}h` : "No queue data loaded yet.";',
    '      els.pageSummary.textContent = summary ? `Page ${filters.page} of ${summary.totalPages}` : `Page ${filters.page}`;',
    '      els.previousPage.disabled = filters.page <= 1;',
    '      els.nextPage.disabled = !(summary && summary.hasNextPage);',
    '      els.projectSummaries.innerHTML = "";',
    '      const allButton = document.createElement("button");',
    '      allButton.type = "button";',
    '      allButton.className = `project-pill${filters.projectId ? "" : " active"}`;',
    '      allButton.textContent = `All projects (${summary ? summary.totalItems : 0})`;',
    '      allButton.addEventListener("click", () => { state.filters.page = 1; els.projectId.value = ""; loadQueue(); });',
    '      els.projectSummaries.appendChild(allButton);',
    '      for (const entry of projectSummaries) {',
    '        const button = document.createElement("button");',
    '        button.type = "button";',
    '        const projectId = entry.project && entry.project.id ? entry.project.id : "";',
    '        button.className = `project-pill${projectId && projectId === filters.projectId ? " active" : ""}`;',
    '        button.innerHTML = `<strong>${escapeHtml(entry.project ? entry.project.name : "Unscoped")}</strong><br /><span class="helper">${entry.queuedCount} queued | impact ${entry.highestImpactScore ?? "n/a"}</span>`;',
    '        button.addEventListener("click", () => { state.filters.page = 1; els.projectId.value = projectId; loadQueue(); });',
    '        els.projectSummaries.appendChild(button);',
    '      }',
    '    }',
    '    function renderQueue() {',
    '      els.queue.innerHTML = "";',
    '      if (!state.items.length) {',
    '        const empty = document.createElement("div");',
    '        empty.className = "empty";',
    '        empty.textContent = "No reports are waiting for review in this filter.";',
    '        els.queue.appendChild(empty);',
    '        return;',
    '      }',
    '      for (const item of state.items) {',
    '        const card = document.createElement("button");',
    '        card.type = "button";',
    '        card.className = `item${state.selected && state.selected.reportId === item.reportId ? " active" : ""}`;',
    '        card.innerHTML = [`<div class="item-header"><input class="item-check" data-role="select" type="checkbox" ${isSelected(item.reportId) ? "checked" : ""} /><div><h3>${escapeHtml(item.title || item.reportId)}</h3><div class="meta"><span class="badge">${escapeHtml(item.project ? item.project.name : "Unscoped project")}</span><span class="badge">${escapeHtml(item.severity)}</span><span class="badge">impact ${item.impactScore ?? "n/a"}</span><span class="badge">${escapeHtml(relativeTime(item.createdAt))}</span></div><div class="helper">${escapeHtml(item.repository || "repository unresolved")} | owner ${escapeHtml(item.owner ? item.owner.label : "unresolved")} | ${escapeHtml(item.reporterIdentifier || "anonymous")} | assigned ${escapeHtml(item.assignedReviewerId || "unassigned")}</div></div></div>`].join("");',
    '        const checkbox = card.querySelector("[data-role=select]");',
    '        if (checkbox) { checkbox.addEventListener("click", (event) => { event.stopPropagation(); }); checkbox.addEventListener("change", () => toggleSelection(item.reportId)); }',
    '        card.addEventListener("click", () => selectItem(item));',
    '        els.queue.appendChild(card);',
    '      }',
    '    }',
    '    function renderSelection() {',
    '      const selected = state.selected;',
    '      const context = state.context;',
    '      if (!selected) {',
    '        els.summary.className = "empty";',
    '        els.summary.textContent = "Select a report to inspect its details.";',
    '        els.context.textContent = "// report evidence appears here";',
    '        els.reviewActivity.innerHTML = `<div class="empty">Select a report to inspect its review history.</div>`;',
    '        renderGuardrails();',
    '        return;',
    '      }',
    '      els.summary.className = "";',
    '      els.summary.innerHTML = [`<div class="row">`,`<span class="badge">${escapeHtml(selected.reportId)}</span>`,`<span class="badge">${escapeHtml(selected.repository || "repository unresolved")}</span>`,`<span class="badge">${escapeHtml(selected.severity)}</span>`,`<span class="badge">owner ${escapeHtml(selected.owner ? selected.owner.label : "unresolved")}</span>`,`<span class="badge">assigned ${escapeHtml(selected.assignedReviewerId || "unassigned")}</span>`,`</div>`,`<p><strong>${escapeHtml(selected.title)}</strong></p>`,`<p>${selected.project ? `${escapeHtml(selected.project.name)} (${escapeHtml(selected.project.projectKey)})` : "No project metadata"}</p>`,`<p>Reporter: ${escapeHtml(selected.reporterIdentifier || "anonymous")}</p>`,`<p class="helper">Created ${escapeHtml(relativeTime(selected.createdAt))} | Updated ${escapeHtml(relativeTime(selected.updatedAt))}</p>`].join("");',
    '      els.repository.value = selected.repository || "";',
    '      els.context.textContent = JSON.stringify(context || {}, null, 2);',
    '      const reviewActivity = Array.isArray(context && context.reviewActivity) ? context.reviewActivity : [];',
    '      els.reviewActivity.innerHTML = reviewActivity.length ? reviewActivity.map((entry) => [`<article class="timeline-entry">`,`<strong>${escapeHtml(entry.summary || entry.eventType || "Activity")}</strong>`,`<div class="helper">${escapeHtml(entry.eventType || "unknown")} | ${escapeHtml(relativeTime(entry.createdAt))} | actor ${escapeHtml(entry.actorId || entry.actorType || "unknown")}</div>`,`</article>`].join("")).join("") : `<div class="empty">No review activity has been recorded yet.</div>`;',
    '      renderGuardrails();',
    '    }',
    '    async function loadQueue() {',
    '      saveAuth();',
    '      setStatus("Loading reports waiting for review...");',
    '      state.filters.projectId = els.projectId.value.trim();',
    '      state.filters.assignedTo = els.assignedTo.value.trim();',
    '      state.filters.search = els.search.value.trim();',
    '      state.filters.sort = els.sort.value;',
    '      const params = new URLSearchParams();',
    '      if (state.filters.projectId) params.set("projectId", state.filters.projectId);',
    '      if (state.filters.assignedTo) params.set("assignedTo", state.filters.assignedTo);',
    '      if (state.filters.search) params.set("search", state.filters.search);',
    '      params.set("page", String(state.filters.page));',
    '      params.set("limit", String(state.filters.limit));',
    '      params.set("sort", state.filters.sort);',
    '      try {',
    '        const data = await request(`/internal/reports/review-queue?${params.toString()}`, { headers: authHeaders() });',
    '        state.items = Array.isArray(data.items) ? data.items : [];',
    '        state.summary = data.summary || null;',
    '        state.selectedIds = state.selectedIds.filter((reportId) => state.items.some((item) => item.reportId === reportId));',
    '        state.filters.page = data.filters && typeof data.filters.page === "number" ? data.filters.page : state.filters.page;',
    '        if (state.selected) {',
    '          state.selected = state.items.find((item) => item.reportId === state.selected.reportId) || null;',
    '        }',
    '        renderSummary();',
    '        renderQueue();',
    '        renderSelection();',
    '        setStatus(`Loaded ${state.items.length} report${state.items.length === 1 ? "" : "s"} on page ${state.filters.page}.`);',
    '      } catch (error) {',
    '        state.summary = null;',
    '        renderSummary();',
    '        renderGuardrails();',
    '        setStatus(error instanceof Error ? error.message : "Failed to load queue.");',
    '      }',
    '    }',
    '    async function selectItem(item) {',
    '      state.selected = item;',
    '      renderQueue();',
    '      setStatus(`Loading evidence for ${item.reportId}...`);',
    '      try {',
    '        state.context = await request(item.contextPath, { headers: authHeaders() });',
    '        renderSelection();',
    '        setStatus(`Loaded evidence for ${item.reportId}.`);',
    '      } catch (error) {',
    '        state.context = null;',
    '        renderSelection();',
    '        setStatus(error instanceof Error ? error.message : "Failed to load report evidence.");',
    '      }',
    '    }',
    '    async function submitReview(status) {',
    '      if (!state.selected) return;',
    '      setStatus(`${status === "approved" ? "Approving" : "Rejecting"} ${state.selected.reportId}...`);',
    '      try {',
    '        const payload = { status, notes: els.notes.value.trim() || undefined, repository: status === "approved" ? (els.repository.value.trim() || undefined) : undefined };',
    '        const result = await request(`/internal/reports/${state.selected.reportId}/review`, { method: "POST", headers: { "content-type": "application/json", ...authHeaders() }, body: JSON.stringify(payload) });',
    '        els.notes.value = "";',
    '        state.context = result;',
    '        await loadQueue();',
    '        setStatus(`${state.selected ? state.selected.reportId : "Report"} ${status}.`);',
    '      } catch (error) {',
    '        setStatus(error instanceof Error ? error.message : "Failed to submit review.");',
    '      }',
    '    }',
    '    async function submitBulkAction(action) {',
    '      if (!state.selectedIds.length) { setStatus("Select at least one report first."); return; }',
    '      setStatus(`${action} ${state.selectedIds.length} report(s)...`);',
    '      const payload = {',
    '        action,',
    '        reportIds: state.selectedIds,',
    '        reviewerId: action === "assign" ? (els.bulkReviewerId.value.trim() || undefined) : undefined,',
    '        repository: action === "approve" ? (els.bulkRepository.value.trim() || undefined) : undefined,',
    '        notes: els.bulkNotes.value.trim() || undefined',
    '      };',
    '      try {',
    '        await request(`/internal/reports/review-queue/actions`, { method: "POST", headers: { "content-type": "application/json", ...authHeaders() }, body: JSON.stringify(payload) });',
    '        els.bulkNotes.value = "";',
    '        if (action !== "assign") { els.bulkRepository.value = ""; }',
    '        clearSelection();',
    '        await loadQueue();',
    '        setStatus(`Bulk ${action} completed.`);',
    '      } catch (error) {',
    '        setStatus(error instanceof Error ? error.message : `Bulk ${action} failed.`);',
    '      }',
    '    }',
    '    const saved = readSaved();',
    '    els.baseUrl.value = saved.baseUrl || window.location.origin;',
    '    els.token.value = saved.token || "";',
    '    els.projectId.value = saved.projectId || "";',
    '    els.assignedTo.value = saved.assignedTo || "";',
    '    els.search.value = saved.search || "";',
    '    els.sort.value = saved.sort || "newest";',
    '    state.filters.projectId = els.projectId.value.trim();',
    '    state.filters.assignedTo = els.assignedTo.value.trim();',
    '    state.filters.search = els.search.value.trim();',
    '    state.filters.sort = els.sort.value;',
    '    els.refresh.addEventListener("click", () => { state.filters.page = 1; loadQueue(); });',
    '    els.clearToken.addEventListener("click", () => { localStorage.removeItem(storageKey); els.token.value = ""; setStatus("Saved auth cleared."); });',
    '    els.previousPage.addEventListener("click", () => { if (state.filters.page > 1) { state.filters.page -= 1; loadQueue(); } });',
    '    els.nextPage.addEventListener("click", () => { state.filters.page += 1; loadQueue(); });',
    '    els.assignedTo.addEventListener("keydown", (event) => { if (event.key === "Enter") { state.filters.page = 1; loadQueue(); } });',
    '    els.search.addEventListener("keydown", (event) => { if (event.key === "Enter") { state.filters.page = 1; loadQueue(); } });',
    '    els.sort.addEventListener("change", () => { state.filters.page = 1; loadQueue(); });',
    '    els.notes.addEventListener("input", renderGuardrails);',
    '    els.repository.addEventListener("input", renderGuardrails);',
    '    els.approve.addEventListener("click", () => submitReview("approved"));',
    '    els.reject.addEventListener("click", () => submitReview("rejected"));',
    '    els.assignSelected.addEventListener("click", () => submitBulkAction("assign"));',
    '    els.approveSelected.addEventListener("click", () => submitBulkAction("approve"));',
    '    els.rejectSelected.addEventListener("click", () => submitBulkAction("reject"));',
    '    els.clearSelection.addEventListener("click", clearSelection);',
    '    renderSummary();',
    '    renderGuardrails();',
    '  </script>',
    '</body>',
    '</html>'
  ].join('\n');
}