export function buildReviewQueuePage(): string {
  return [
    '<!DOCTYPE html>',
    '<html lang="en">',
    '<head>',
    '  <meta charset="utf-8" />',
    '  <meta name="viewport" content="width=device-width, initial-scale=1" />',
    '  <title>Nexus Review Queue</title>',
    '  <style>',
    '    :root { color-scheme: light; --bg-top: #f8f1dd; --bg-bottom: #d7e2db; --ink: #18212b; --muted: rgba(24,33,43,0.68); --panel: rgba(255,255,255,0.84); --panel-strong: rgba(255,255,255,0.94); --line: rgba(24,33,43,0.12); --accent: #0d5e55; --accent-soft: rgba(13,94,85,0.12); --accent-ink: #0a3d37; --good: #0f6b46; --bad: #922f2f; --warn: #8b6208; --shadow: 0 22px 56px rgba(24,33,43,0.12); }',
    '    * { box-sizing: border-box; }',
    '    body { margin: 0; font-family: "Iowan Old Style", Georgia, serif; color: var(--ink); background: radial-gradient(circle at top left, #fff8eb 0%, var(--bg-top) 36%, var(--bg-bottom) 100%); }',
    '    main { max-width: 1340px; margin: 0 auto; padding: 36px 18px 60px; }',
    '    h1 { margin: 0 0 10px; font-size: clamp(2.7rem, 5vw, 5rem); line-height: 0.92; max-width: 12ch; }',
    '    p { color: var(--muted); max-width: 76ch; line-height: 1.6; }',
    '    .eyebrow { display: inline-block; margin-bottom: 14px; padding: 8px 10px; border-radius: 999px; background: var(--accent-soft); color: var(--accent); font: 600 0.76rem/1.1 ui-monospace, SFMono-Regular, Menlo, monospace; text-transform: uppercase; letter-spacing: 0.08em; }',
    '    .hero { display: grid; gap: 20px; }',
    '    .hero-grid { display: grid; grid-template-columns: minmax(0, 1.5fr) minmax(280px, 0.9fr); gap: 18px; align-items: end; }',
    '    .summary-grid { display: grid; grid-template-columns: repeat(4, minmax(0, 1fr)); gap: 14px; }',
    '    .summary-card { background: linear-gradient(180deg, rgba(255,255,255,0.95), rgba(255,255,255,0.76)); border: 1px solid rgba(255,255,255,0.5); border-radius: 24px; padding: 18px; box-shadow: var(--shadow); min-height: 120px; }',
    '    .summary-label { display: block; color: var(--muted); font: 600 0.78rem/1.2 ui-monospace, SFMono-Regular, Menlo, monospace; text-transform: uppercase; letter-spacing: 0.08em; }',
    '    .summary-value { display: block; margin-top: 10px; font-size: clamp(1.8rem, 4vw, 3rem); line-height: 0.95; }',
    '    .summary-note { margin-top: 10px; font-size: 0.95rem; color: var(--muted); }',
    '    .shell { display: grid; grid-template-columns: 390px minmax(0, 1fr); gap: 18px; margin-top: 28px; }',
    '    .panel { background: var(--panel); border: 1px solid var(--line); border-radius: 28px; box-shadow: var(--shadow); overflow: hidden; backdrop-filter: blur(10px); }',
    '    .controls { padding: 18px; display: grid; gap: 12px; }',
    '    label { display: grid; gap: 6px; font-size: 0.92rem; color: var(--muted); }',
    '    input, textarea, button, select { font: inherit; }',
    '    input, textarea, select { width: 100%; border: 1px solid var(--line); border-radius: 14px; padding: 11px 12px; background: var(--panel-strong); color: var(--ink); }',
    '    textarea { min-height: 96px; resize: vertical; }',
    '    button { border: none; border-radius: 14px; padding: 12px 14px; cursor: pointer; transition: transform 140ms ease, opacity 140ms ease; }',
    '    button:hover { transform: translateY(-1px); }',
    '    button.primary { background: var(--accent); color: #fffaf6; }',
    '    button.secondary { background: rgba(255,255,255,0.86); border: 1px solid var(--line); color: var(--ink); }',
    '    button.success { background: var(--good); color: white; }',
    '    button.danger { background: var(--bad); color: white; }',
    '    button:disabled { opacity: 0.5; cursor: not-allowed; transform: none; }',
    '    .list { display: grid; gap: 10px; padding: 0 18px 18px; max-height: 640px; overflow: auto; }',
    '    .item { width: 100%; text-align: left; border: 1px solid var(--line); border-radius: 20px; padding: 14px; background: rgba(255,255,255,0.72); cursor: pointer; }',
    '    .item.active { border-color: rgba(13,94,85,0.45); box-shadow: inset 0 0 0 1px rgba(13,94,85,0.2); background: rgba(239,249,246,0.96); }',
    '    .item-header { display: flex; gap: 10px; align-items: flex-start; }',
    '    .item-check { margin-top: 2px; width: 18px; height: 18px; accent-color: var(--accent); }',
    '    .item h3 { margin: 0 0 8px; font-size: 1.04rem; }',
    '    .meta { display: flex; flex-wrap: wrap; gap: 8px; font-size: 0.8rem; color: var(--muted); }',
    '    .badge { display: inline-flex; align-items: center; gap: 6px; border-radius: 999px; padding: 6px 9px; background: #eef4f2; }',
    '    .stack { display: grid; gap: 14px; }',
    '    .summary-strip { display: grid; gap: 10px; grid-template-columns: repeat(auto-fit, minmax(180px, 1fr)); }',
    '    .mini-card { border: 1px solid var(--line); border-radius: 18px; padding: 14px; background: rgba(255,255,255,0.78); }',
    '    .bulk-box { display: grid; gap: 10px; }',
    '    .project-pills { display: flex; flex-wrap: wrap; gap: 10px; }',
    '    .project-pill { border: 1px solid var(--line); background: rgba(255,255,255,0.72); color: var(--ink); padding: 10px 12px; border-radius: 16px; text-align: left; }',
    '    .project-pill.active { background: rgba(13,94,85,0.14); border-color: rgba(13,94,85,0.35); color: var(--accent-ink); }',
    '    .workspace { padding: 18px; display: grid; gap: 16px; min-height: 760px; }',
    '    .workspace pre { margin: 0; padding: 14px; border-radius: 16px; background: #231f20; color: #f7efe3; overflow: auto; font: 0.82rem/1.45 ui-monospace, SFMono-Regular, Menlo, monospace; }',
    '    .empty { display: grid; place-items: center; min-height: 280px; color: var(--muted); border: 1px dashed var(--line); border-radius: 18px; }',
    '    .split { display: grid; grid-template-columns: repeat(2, minmax(0, 1fr)); gap: 14px; }',
    '    .insight-grid { display: grid; gap: 10px; grid-template-columns: repeat(auto-fit, minmax(180px, 1fr)); }',
    '    .insight-card { border: 1px solid var(--line); border-radius: 18px; padding: 14px; background: rgba(255,255,255,0.78); }',
    '    .insight-card strong { display: block; margin-bottom: 6px; font-size: 0.92rem; }',
    '    .insight-card span { display: block; color: var(--muted); font-size: 0.84rem; line-height: 1.45; }',
    '    .result-card { border: 1px solid var(--line); border-radius: 18px; padding: 16px; background: rgba(255,255,255,0.78); }',
    '    .result-card.success { border-color: rgba(13,94,85,0.28); background: rgba(13,94,85,0.08); }',
    '    .result-card.warning { border-color: rgba(139,98,8,0.26); background: rgba(139,98,8,0.09); }',
    '    .result-card strong { display: block; margin-bottom: 8px; }',
    '    .reviewed-list { display: grid; gap: 10px; padding: 0 18px 18px; border-top: 1px solid var(--line); max-height: 260px; overflow: auto; }',
    '    .reviewed-item { width: 100%; text-align: left; border: 1px solid var(--line); border-radius: 18px; padding: 12px; background: rgba(255,255,255,0.7); cursor: pointer; }',
    '    .reviewed-item.active { border-color: rgba(13,94,85,0.45); box-shadow: inset 0 0 0 1px rgba(13,94,85,0.2); background: rgba(239,249,246,0.96); }',
    '    details summary { cursor: pointer; color: var(--muted); margin-bottom: 8px; }',
    '    .task-panel { display: grid; gap: 12px; }',
    '    .task-actions { display: flex; gap: 10px; flex-wrap: wrap; }',
    '    .task-status-grid { display: grid; gap: 10px; grid-template-columns: repeat(auto-fit, minmax(180px, 1fr)); }',
    '    .task-status-card { border: 1px solid var(--line); border-radius: 18px; padding: 14px; background: rgba(255,255,255,0.78); }',
    '    .task-status-card strong { display: block; margin-bottom: 6px; }',
    '    .task-status-card span { display: block; color: var(--muted); font-size: 0.84rem; line-height: 1.45; }',
    '    .detail-stack { display: grid; gap: 12px; }',
    '    .detail-card { border: 1px solid var(--line); border-radius: 18px; padding: 14px; background: rgba(255,255,255,0.78); }',
    '    .detail-card h3 { margin: 0 0 8px; font-size: 0.98rem; }',
    '    .detail-list { margin: 0; padding-left: 18px; color: var(--muted); font-size: 0.9rem; line-height: 1.5; }',
    '    .detail-list li + li { margin-top: 6px; }',
    '    .gate-grid { display: grid; gap: 10px; grid-template-columns: repeat(auto-fit, minmax(160px, 1fr)); }',
    '    .gate-card { border: 1px solid var(--line); border-radius: 16px; padding: 12px; background: rgba(255,255,255,0.76); }',
    '    .gate-card strong { display: block; margin-bottom: 4px; font-size: 0.9rem; }',
    '    .gate-card span { display: block; color: var(--muted); font-size: 0.82rem; line-height: 1.4; }',
    '    .gate-pass { border-color: rgba(13,94,85,0.28); background: rgba(13,94,85,0.08); }',
    '    .gate-fail { border-color: rgba(146,47,47,0.25); background: rgba(146,47,47,0.08); }',
    '    .gate-warn { border-color: rgba(139,98,8,0.26); background: rgba(139,98,8,0.09); }',
    '    .gate-neutral { border-color: var(--line); }',
    '    .status { padding: 12px 14px; border-top: 1px solid var(--line); background: rgba(31,36,48,0.03); color: var(--muted); min-height: 48px; }',
    '    .row { display: flex; gap: 10px; flex-wrap: wrap; }',
    '    .row.spread { justify-content: space-between; align-items: center; }',
    '    .section-title { margin: 0; font-size: 0.9rem; letter-spacing: 0.04em; text-transform: uppercase; color: var(--muted); }',
    '    .helper { font-size: 0.85rem; color: var(--muted); }',
    '    .timeline { display: grid; gap: 10px; }',
    '    .timeline-entry { border: 1px solid var(--line); border-radius: 16px; padding: 12px; background: rgba(255,255,255,0.78); }',
    '    .timeline-entry strong { display: block; margin-bottom: 4px; }',
    '    .pager { display: flex; gap: 10px; align-items: center; justify-content: space-between; padding: 0 18px 18px; }',
    '    .pager-group { display: flex; gap: 10px; align-items: center; }',
    '    .guardrail-grid { display: grid; gap: 10px; grid-template-columns: repeat(4, minmax(0, 1fr)); }',
    '    .guardrail-card { border: 1px solid var(--line); border-radius: 18px; padding: 14px; background: rgba(255,255,255,0.78); }',
    '    .guardrail-card strong { display: block; font-size: 0.94rem; }',
    '    .guardrail-card span { display: block; margin-top: 8px; color: var(--muted); font-size: 0.84rem; line-height: 1.45; }',
    '    .guardrail-pass { border-color: rgba(13,94,85,0.28); background: rgba(13,94,85,0.08); }',
    '    .guardrail-pass strong { color: var(--accent); }',
    '    .guardrail-fail { border-color: rgba(139,98,8,0.26); background: rgba(139,98,8,0.09); }',
    '    .guardrail-fail strong { color: var(--warn); }',
    '    .guardrail-neutral { border-color: var(--line); }',
    '    @media (max-width: 1120px) { .hero-grid, .shell, .split { grid-template-columns: 1fr; } .summary-grid { grid-template-columns: repeat(2, minmax(0, 1fr)); } }',
    '    @media (max-width: 680px) { .summary-grid { grid-template-columns: 1fr; } main { padding-inline: 12px; } }',
    '  </style>',
    '</head>',
    '<body>',
    '  <main>',
    '    <section class="hero">',
    '      <span class="eyebrow">Review • Decide</span>',
    '      <div class="hero-grid">',
    '        <div>',
    '          <h1>Review reports before anything moves into GitHub.</h1>',
    '          <p>This queue should help an operator make the next decision quickly. Load the report, inspect the evidence, and approve or reject the downstream action only when the target, context, and notes are clear.</p>',
    '        </div>',
    '        <div class="summary-grid">',
    '          <article class="summary-card"><span class="summary-label">Reports Waiting</span><span id="queuedCount" class="summary-value">0</span><span class="summary-note" id="queuedNote">Reports visible in the current filter.</span></article>',
    '          <article class="summary-card"><span class="summary-label">Needs Attention</span><span id="criticalCount" class="summary-value">0</span><span class="summary-note">Critical reports still waiting on review.</span></article>',
    '          <article class="summary-card"><span class="summary-label">Projects</span><span id="projectCount" class="summary-value">0</span><span class="summary-note">Projects represented in this review slice.</span></article>',
    '          <article class="summary-card"><span class="summary-label">Page</span><span id="pageValue" class="summary-value">1</span><span class="summary-note" id="pageNote">Current page and sort state.</span></article>',
    '        </div>',
    '      </div>',
    '    </section>',
    '    <section class="shell">',
    '      <aside class="panel">',
    '        <div class="controls">',
    '          <label>Base URL<input id="baseUrl" value="" placeholder="http://127.0.0.1:4000" /></label>',
    '          <label>Bearer Token (optional)<input id="token" value="" placeholder="nexus-local-dev-token" /></label>',
    '          <label>Project Id Filter<input id="projectId" value="" placeholder="Optional project UUID" /></label>',
    '          <label>Assigned To<input id="assignedTo" value="" placeholder="Filter by reviewer or operator id" /></label>',
    '          <label>Search Reports<input id="search" value="" placeholder="Project, repo, title, reporter" /></label>',
    '          <label>Sort By<select id="sort"><option value="newest">Newest first</option><option value="oldest">Oldest first</option><option value="impact">Highest impact</option><option value="severity">Highest severity</option></select></label>',
    '          <div class="row">',
    '            <button id="refresh" class="primary">Load Reports</button>',
    '            <button id="clearToken" class="secondary">Clear Saved Auth</button>',
    '          </div>',
    '          <div class="stack">',
    '            <h2 class="section-title">Project Queues</h2>',
    '            <div id="projectSummaries" class="project-pills"></div>',
    '          </div>',
    '          <div class="bulk-box">',
    '            <h2 class="section-title">Batch Decisions</h2>',
    '            <label>Assign Selected To<input id="bulkReviewerId" value="" placeholder="defaults to your operator id" /></label>',
    '            <label>Bulk Repository Override<input id="bulkRepository" value="" placeholder="owner/repo optional" /></label>',
    '            <label>Bulk Notes<textarea id="bulkNotes" placeholder="Applied to selected queued reports."></textarea></label>',
    '            <div class="row">',
    '              <button id="assignSelected" class="secondary">Assign</button>',
    '              <button id="approveSelected" class="success">Approve Selected</button>',
    '              <button id="rejectSelected" class="danger">Reject Selected</button>',
    '              <button id="clearSelection" class="secondary">Clear</button>',
    '            </div>',
    '          </div>',
    '        </div>',
    '        <div id="queue" class="list"></div>',
    '        <div class="stack" style="padding: 0 18px 18px; border-top: 1px solid var(--line);">',
    '          <h2 class="section-title">Reviewed History</h2>',
    '          <div id="reviewedHistory" class="reviewed-list"><div class="helper">Approved and rejected reports you touch in this browser stay inspectable here.</div></div>',
    '        </div>',
    '        <div class="pager">',
    '          <div class="pager-group">',
    '            <button id="previousPage" class="secondary">Previous</button>',
    '            <button id="nextPage" class="secondary">Next</button>',
    '          </div>',
    '          <div class="helper" id="pageSummary">Page 1</div>',
    '        </div>',
    '        <div id="queueStatus" class="status">Queue not loaded yet.</div>',
    '      </aside>',
    '      <section class="panel workspace">',
    '        <div class="summary-strip">',
    '          <article class="mini-card"><h2 class="section-title">Queue Mix</h2><div id="severitySummary" class="helper">No queue data loaded yet.</div></article>',
    '          <article class="mini-card"><h2 class="section-title">Filter State</h2><div id="filterSummary" class="helper">No filters applied.</div></article>',
    '          <article class="mini-card"><h2 class="section-title">Queue Window</h2><div id="windowSummary" class="helper">Waiting for queue data.</div></article>',
    '          <article class="mini-card"><h2 class="section-title">Approval Health</h2><div id="workflowSummary" class="helper">No queue data loaded yet.</div></article>',
    '        </div>',
    '        <div>',
    '          <h2 class="section-title">Approval Checklist</h2>',
    '          <div class="guardrail-grid">',
    '            <article id="guardrailTarget" class="guardrail-card guardrail-neutral"><strong>No report selected</strong><span>Select a report before making an approval decision.</span></article>',
    '            <article id="guardrailContext" class="guardrail-card guardrail-neutral"><strong>Evidence not loaded</strong><span>Load the report context before acting.</span></article>',
    '            <article id="guardrailRationale" class="guardrail-card guardrail-neutral"><strong>Decision notes missing</strong><span>Add notes so the approval or rejection has clear operator reasoning.</span></article>',
    '            <article id="guardrailPromotion" class="guardrail-card guardrail-neutral"><strong>Approval is blocked</strong><span>Approval stays blocked until target, evidence, and notes are all visible.</span></article>',
    '          </div>',
    '        </div>',
    '        <div class="split">',
    '          <div>',
    '            <h2 class="section-title">Selected Report</h2>',
    '            <div id="summary" class="empty">Select a report to inspect its details.</div>',
    '          </div>',
    '          <div>',
    '            <h2 class="section-title">Review Decision</h2>',
    '            <label>Repository Override<input id="repository" value="" placeholder="owner/repo optional" /></label>',
    '            <label>Notes<textarea id="notes" placeholder="Record why this was approved or rejected."></textarea></label>',
    '            <div class="row">',
    '              <button id="approve" class="success" disabled>Approve Report</button>',
    '              <button id="reject" class="danger" disabled>Reject Report</button>',
    '            </div>',
    '          </div>',
    '        </div>',
    '        <div>',
    '          <h2 class="section-title">Decision Result</h2>',
    '          <div id="decisionResult" class="empty">Approve or reject a report to capture the downstream handoff here.</div>',
    '        </div>',
    '        <div>',
    '          <h2 class="section-title">Agent Handoff</h2>',
    '          <div id="agentTaskPanel" class="empty">Approve a report to create an agent task and launch an isolated branch execution.</div>',
    '        </div>',
    '        <div>',
    '          <h2 class="section-title">Operator Summary</h2>',
    '          <div id="contextSummary" class="empty">Load a report to see the decision-ready summary before the raw JSON.</div>',
    '        </div>',
    '        <div>',
    '          <h2 class="section-title">Raw Evidence</h2>',
    '          <details>',
    '            <summary>Show full report JSON</summary>',
    '            <pre id="context">// report evidence appears here</pre>',
    '          </details>',
    '        </div>',
    '        <div>',
    '          <h2 class="section-title">Review History</h2>',
    '          <div id="reviewActivity" class="timeline"><div class="empty">Select a report to inspect its review history.</div></div>',
    '        </div>',
    '      </section>',
    '    </section>',
    '  </main>',
    '  <script>',
    '    const storageKey = "nexus-review-queue-auth";',
    '    const reviewedHistoryKey = "nexus-review-queue-reviewed-history";',
    '    const decisionResultKey = "nexus-review-queue-last-result";',
    '    const state = { items: [], selected: null, selectedIds: [], context: null, summary: null, reviewedItems: [], lastDecision: null, latestExecutionDetail: null, latestExecutionCloseout: null, latestExecutionReview: null, latestExecutionPullRequest: null, latestExecutionValidationPolicy: null, latestReplayValidation: null, filters: { page: 1, limit: 12, sort: "newest", projectId: "", assignedTo: "", search: "" } };',
    '    const els = {',
    '      baseUrl: document.getElementById("baseUrl"),',
    '      token: document.getElementById("token"),',
    '      projectId: document.getElementById("projectId"),',
    '      assignedTo: document.getElementById("assignedTo"),',
    '      search: document.getElementById("search"),',
    '      sort: document.getElementById("sort"),',
    '      refresh: document.getElementById("refresh"),',
    '      clearToken: document.getElementById("clearToken"),',
    '      previousPage: document.getElementById("previousPage"),',
    '      nextPage: document.getElementById("nextPage"),',
    '      queue: document.getElementById("queue"),',
    '      queueStatus: document.getElementById("queueStatus"),',
    '      bulkReviewerId: document.getElementById("bulkReviewerId"),',
    '      bulkRepository: document.getElementById("bulkRepository"),',
    '      bulkNotes: document.getElementById("bulkNotes"),',
    '      assignSelected: document.getElementById("assignSelected"),',
    '      approveSelected: document.getElementById("approveSelected"),',
    '      rejectSelected: document.getElementById("rejectSelected"),',
    '      clearSelection: document.getElementById("clearSelection"),',
    '      reviewedHistory: document.getElementById("reviewedHistory"),',
    '      projectSummaries: document.getElementById("projectSummaries"),',
    '      pageSummary: document.getElementById("pageSummary"),',
    '      queuedCount: document.getElementById("queuedCount"),',
    '      queuedNote: document.getElementById("queuedNote"),',
    '      criticalCount: document.getElementById("criticalCount"),',
    '      projectCount: document.getElementById("projectCount"),',
    '      pageValue: document.getElementById("pageValue"),',
    '      pageNote: document.getElementById("pageNote"),',
    '      severitySummary: document.getElementById("severitySummary"),',
    '      filterSummary: document.getElementById("filterSummary"),',
    '      windowSummary: document.getElementById("windowSummary"),',
    '      workflowSummary: document.getElementById("workflowSummary"),',
    '      summary: document.getElementById("summary"),',
    '      repository: document.getElementById("repository"),',
    '      notes: document.getElementById("notes"),',
    '      approve: document.getElementById("approve"),',
    '      reject: document.getElementById("reject"),',
    '      decisionResult: document.getElementById("decisionResult"),',
    '      agentTaskPanel: document.getElementById("agentTaskPanel"),',
    '      contextSummary: document.getElementById("contextSummary"),',
    '      context: document.getElementById("context"),',
    '      reviewActivity: document.getElementById("reviewActivity"),',
    '      guardrailTarget: document.getElementById("guardrailTarget"),',
    '      guardrailContext: document.getElementById("guardrailContext"),',
    '      guardrailRationale: document.getElementById("guardrailRationale"),',
    '      guardrailPromotion: document.getElementById("guardrailPromotion")',
    '    };',
    '    function readSaved() {',
    '      try { return JSON.parse(localStorage.getItem(storageKey) || "{}"); } catch { return {}; }',
    '    }',
    '    function saveAuth() {',
    '      localStorage.setItem(storageKey, JSON.stringify({ baseUrl: els.baseUrl.value.trim(), token: els.token.value.trim(), projectId: els.projectId.value.trim(), assignedTo: els.assignedTo.value.trim(), search: els.search.value.trim(), sort: els.sort.value }));',
    '    }',
    '    function readReviewedHistory() {',
    '      try { const value = JSON.parse(localStorage.getItem(reviewedHistoryKey) || "[]"); return Array.isArray(value) ? value : []; } catch { return []; }',
    '    }',
    '    function saveReviewedHistory() {',
    '      localStorage.setItem(reviewedHistoryKey, JSON.stringify(state.reviewedItems.slice(0, 12)));',
    '    }',
    '    function readLastDecision() {',
    '      try { return JSON.parse(localStorage.getItem(decisionResultKey) || "null"); } catch { return null; }',
    '    }',
    '    function saveLastDecision() {',
    '      localStorage.setItem(decisionResultKey, JSON.stringify(state.lastDecision));',
    '    }',
    '    function setStatus(message) { els.queueStatus.textContent = message; }',
    '    function authHeaders() {',
    '      const token = els.token.value.trim();',
    '      return token ? { Authorization: `Bearer ${token}` } : {};',
    '    }',
    '    function sleep(milliseconds) { return new Promise((resolve) => setTimeout(resolve, milliseconds)); }',
    '    function escapeHtml(value) {',
    '      return String(value ?? "").replace(/[&<>"\']/g, (character) => {',
    '        if (character === "&") return "&amp;";',
    '        if (character === "<") return "&lt;";',
    '        if (character === ">") return "&gt;";',
    '        if (character.charCodeAt(0) === 34) return "&quot;";',
    '        if (character.charCodeAt(0) === 39) return "&#39;";',
    '        return character;',
    '      });',
    '    }',
    '    function relativeTime(value) {',
    '      if (!value) return "unknown";',
    '      const milliseconds = Date.now() - new Date(value).getTime();',
    '      const minutes = Math.round(milliseconds / 60000);',
    '      if (!Number.isFinite(minutes)) return "unknown";',
    '      if (Math.abs(minutes) < 60) return `${minutes}m ago`;',
    '      const hours = Math.round(minutes / 60);',
    '      if (Math.abs(hours) < 48) return `${hours}h ago`;',
    '      const days = Math.round(hours / 24);',
    '      return `${days}d ago`;',
    '    }',
    '    function isSelected(reportId) { return state.selectedIds.includes(reportId); }',
    '    function selectedItems() { return state.items.filter((item) => state.selectedIds.includes(item.reportId)); }',
    '    function isReviewedSelection() { return Boolean(state.selected && state.selected.reviewStatus && state.selected.reviewStatus !== "pending"); }',
    '    function reviewStatusFromContext(context, selected) {',
    '      return context && context.reportReview && context.reportReview.status ? context.reportReview.status : (selected && selected.reviewStatus ? selected.reviewStatus : "pending");',
    '    }',
    '    function latestAgentTask(context) {',
    '      const tasks = context && Array.isArray(context.agentTasks) ? context.agentTasks : [];',
    '      return tasks.length ? tasks[0] : null;',
    '    }',
    '    function latestAgentExecution(task) {',
    '      const executions = task && Array.isArray(task.executions) ? task.executions : [];',
    '      return executions.length ? executions[0] : null;',
    '    }',
    '    function defaultAgentTaskObjective(selected) {',
    '      const repository = selected && selected.repository ? selected.repository : "the approved repository";',
    '      const title = selected && selected.title ? selected.title : "the approved report";',
    '      return `Investigate ${title} in ${repository} and prepare a scoped fix or clear remediation plan for the affected flow.`;',
    '    }',
    '    function defaultAcceptanceCriteria(selected) {',
    '      const repository = selected && selected.repository ? selected.repository : "the approved repository";',
    '      return [`Stay scoped to ${repository}.`,`Explain the suspected root cause using the approved report evidence.`,`If code changes are proposed, keep them isolated to the affected flow.`,`Include validation evidence or a clear reason validation could not run.`].join("\\n");',
    '    }',
    '    async function pollAgentTask(taskId, attempts = 20, delayMs = 1500) {',
    '      let lastTask = null;',
    '      for (let attempt = 0; attempt < attempts; attempt += 1) {',
    '        lastTask = await request(`/internal/agent-tasks/${taskId}`, { headers: authHeaders() });',
    '        if (lastTask && ["ready", "completed", "failed", "cancelled"].includes(lastTask.status)) {',
    '          return lastTask;',
    '        }',
    '        await sleep(delayMs);',
    '      }',
    '      return lastTask;',
    '    }',
    '    async function pollExecution(executionId, attempts = 20, delayMs = 1500) {',
    '      let lastExecution = null;',
    '      for (let attempt = 0; attempt < attempts; attempt += 1) {',
    '        lastExecution = await request(`/internal/agent-task-executions/${executionId}`, { headers: authHeaders() });',
    '        if (lastExecution && !["queued", "running"].includes(lastExecution.status)) {',
    '          return lastExecution;',
    '        }',
    '        await sleep(delayMs);',
    '      }',
    '      return lastExecution;',
    '    }',
    '    async function requestOptional(path, init, acceptedStatuses = [404]) {',
    '      const baseUrl = els.baseUrl.value.trim() || window.location.origin;',
    '      const response = await fetch(baseUrl + path, init);',
    '      if (acceptedStatuses.includes(response.status)) {',
    '        return null;',
    '      }',
    '      const text = await response.text();',
    '      if (!response.ok) { throw new Error(`${init && init.method ? init.method : "GET"} ${path} failed: ${response.status} ${text}`); }',
    '      return text ? JSON.parse(text) : null;',
    '    }',
    '    async function refreshExecutionState(executionId) {',
    '      if (!executionId) {',
    '        state.latestExecutionDetail = null;',
    '        state.latestExecutionCloseout = null;',
    '        state.latestExecutionReview = null;',
    '        state.latestExecutionPullRequest = null;',
    '        state.latestExecutionValidationPolicy = null;',
    '        state.latestReplayValidation = null;',
    '        return;',
    '      }',
    '      const [detail, closeout, review, pullRequest, validationPolicy, replayValidation] = await Promise.all([',
    '        request(`/internal/agent-task-executions/${executionId}`, { headers: authHeaders() }),',
    '        request(`/internal/agent-task-executions/${executionId}/closeout`, { headers: authHeaders() }),',
    '        request(`/internal/agent-task-executions/${executionId}/review`, { headers: authHeaders() }),',
    '        requestOptional(`/internal/agent-task-executions/${executionId}/pull-request`, { headers: authHeaders() }),',
    '        requestOptional(`/internal/agent-task-executions/${executionId}/validation-policy`, { headers: authHeaders() }),',
    '        requestOptional(`/internal/agent-task-executions/${executionId}/replay-validation`, { headers: authHeaders() })',
    '      ]);',
    '      state.latestExecutionDetail = detail;',
    '      state.latestExecutionCloseout = closeout;',
    '      state.latestExecutionReview = review;',
    '      state.latestExecutionPullRequest = pullRequest;',
    '      state.latestExecutionValidationPolicy = validationPolicy;',
    '      state.latestReplayValidation = replayValidation;',
    '    }',
    '    async function refreshSelectedContext() {',
    '      if (!state.selected) {',
    '        state.context = null;',
    '        state.latestExecutionDetail = null;',
    '        state.latestExecutionCloseout = null;',
    '        state.latestExecutionReview = null;',
    '        state.latestExecutionPullRequest = null;',
    '        state.latestExecutionValidationPolicy = null;',
    '        state.latestReplayValidation = null;',
    '        return null;',
    '      }',
    '      state.context = await request(state.selected.contextPath, { headers: authHeaders() });',
    '      const task = latestAgentTask(state.context);',
    '      const execution = latestAgentExecution(task);',
    '      if (!execution) {',
    '        await refreshExecutionState(null);',
    '        return state.context;',
    '      }',
    '      await refreshExecutionState(execution.id);',
    '      return state.context;',
    '    }',
    '    function gateTone(status) {',
    '      if (["passed", "ready", "opened", "merged", "approved"].includes(status)) return "pass";',
    '      if (["failed", "rejected", "blocked"].includes(status)) return "fail";',
    '      if (["pending", "not-run"].includes(status)) return "warn";',
    '      return "neutral";',
    '    }',
    '    function renderList(items, emptyMessage) {',
    '      if (!Array.isArray(items) || !items.length) {',
    '        return `<div class="helper">${escapeHtml(emptyMessage)}</div>`;',
    '      }',
    '      return `<ul class="detail-list">${items.map((item) => `<li>${escapeHtml(item)}</li>`).join("")}</ul>`;',
    '    }',
    '    function valueOrFallback(value, fallback = "Not available") {',
    '      return value === null || value === undefined || value === "" ? fallback : String(value);',
    '    }',
    '    function resolveSharedSelectedRepository() {',
    '      const repositories = Array.from(new Set(selectedItems().map((item) => item.repository).filter(Boolean)));',
    '      return repositories.length === 1 ? repositories[0] : "";',
    '    }',
    '    function clearSelection() { state.selectedIds = []; renderQueue(); renderSummary(); }',
    '    function upsertReviewedItem(item) {',
    '      state.reviewedItems = [item, ...state.reviewedItems.filter((entry) => entry.reportId !== item.reportId)].slice(0, 12);',
    '      saveReviewedHistory();',
    '      renderReviewedHistory();',
    '    }',
    '    function renderReviewedHistory() {',
    '      els.reviewedHistory.innerHTML = "";',
    '      if (!state.reviewedItems.length) {',
    '        els.reviewedHistory.innerHTML = `<div class="helper">Approved and rejected reports you touch in this browser stay inspectable here.</div>`;',
    '        return;',
    '      }',
    '      for (const item of state.reviewedItems) {',
    '        const button = document.createElement("button");',
    '        button.type = "button";',
    '        button.className = `reviewed-item${state.selected && state.selected.reportId === item.reportId ? " active" : ""}`;',
    '        button.innerHTML = [`<strong>${escapeHtml(item.title || item.reportId)}</strong>`,`<div class="meta"><span class="badge">${escapeHtml(item.reviewStatus || "reviewed")}</span><span class="badge">${escapeHtml(item.draftState || "no-draft-state")}</span><span class="badge">${escapeHtml(relativeTime(item.reviewedAt || item.updatedAt))}</span></div>`,`<div class="helper">${escapeHtml(item.repository || "repository unresolved")}${item.issueUrl ? ` | GitHub draft ready` : item.syncError ? ` | ${escapeHtml(item.syncError)}` : ""}</div>`].join("");',
    '        button.addEventListener("click", () => selectItem(item));',
    '        els.reviewedHistory.appendChild(button);',
    '      }',
    '    }',
    '    function toggleSelection(reportId) {',
    '      state.selectedIds = isSelected(reportId) ? state.selectedIds.filter((id) => id !== reportId) : [...state.selectedIds, reportId];',
    '      renderQueue();',
    '      renderSummary();',
    '    }',
    '    async function request(path, init) {',
    '      const baseUrl = els.baseUrl.value.trim() || window.location.origin;',
    '      const response = await fetch(baseUrl + path, init);',
    '      const text = await response.text();',
    '      if (!response.ok) { throw new Error(`${init && init.method ? init.method : "GET"} ${path} failed: ${response.status} ${text}`); }',
    '      return JSON.parse(text);',
    '    }',
    '    function renderGuardrailCard(target, tone, title, detail) {',
    '      target.className = `guardrail-card guardrail-${tone}`;',
    '      target.innerHTML = `<strong>${escapeHtml(title)}</strong><span>${escapeHtml(detail)}</span>`;',
    '    }',
    '    function canRejectSelection() {',
    '      return Boolean(state.selected && !isReviewedSelection() && els.notes.value.trim());',
    '    }',
    '    function canApproveSelection() {',
    '      const repositoryTarget = els.repository.value.trim() || (state.selected && state.selected.repository) || "";',
    '      return Boolean(state.selected && !isReviewedSelection() && state.context && els.notes.value.trim() && repositoryTarget);',
    '    }',
    '    function renderDecisionResult() {',
    '      const decision = state.lastDecision;',
    '      if (!decision) {',
    '        els.decisionResult.className = "empty";',
    '        els.decisionResult.textContent = "Approve or reject a report to capture the downstream handoff here.";',
    '        return;',
    '      }',
    '      const tone = decision.syncError ? "warning" : "success";',
    '      const title = decision.reviewStatus === "approved" ? "Review approved" : "Review rejected";',
    '      const destination = decision.issueUrl ? `<a href="${escapeHtml(decision.issueUrl)}" target="_blank" rel="noreferrer">Open GitHub draft</a>` : (decision.syncError ? escapeHtml(decision.syncError) : "No GitHub draft URL was returned.");',
    '      els.decisionResult.className = `result-card ${tone}`;',
    '      els.decisionResult.innerHTML = [`<strong>${escapeHtml(title)} for ${escapeHtml(decision.reportId)}</strong>`,`<div class="helper">Repository ${escapeHtml(decision.repository || "unresolved")} | draft state ${escapeHtml(decision.draftState || "unknown")} | reviewed ${escapeHtml(relativeTime(decision.reviewedAt))}</div>`,`<p>${escapeHtml(decision.message || "The report moved out of the pending inbox.")}</p>`,`<div class="helper">${decision.issueUrl ? destination : destination}</div>`].join("");',
    '    }',
    '    function renderAgentTaskPanel() {',
    '      const selected = state.selected;',
    '      const context = state.context;',
    '      if (!selected || !context) {',
    '        els.agentTaskPanel.className = "empty";',
    '        els.agentTaskPanel.textContent = "Approve a report to create an agent task and launch an isolated branch execution.";',
    '        return;',
    '      }',
    '      const reviewStatus = reviewStatusFromContext(context, selected);',
    '      if (reviewStatus !== "approved") {',
    '        els.agentTaskPanel.className = "empty";',
    '        els.agentTaskPanel.textContent = "Approve this report first. Agent tasks only unlock after an approved hosted-feedback review.";',
    '        return;',
    '      }',
    '      const task = latestAgentTask(context);',
    '      const execution = latestAgentExecution(task);',
    '      const executionDetail = state.latestExecutionDetail && execution && state.latestExecutionDetail.id === execution.id ? state.latestExecutionDetail : null;',
    '      const executionCloseout = state.latestExecutionCloseout && execution && state.latestExecutionCloseout.executionId === execution.id ? state.latestExecutionCloseout : null;',
    '      const executionReview = state.latestExecutionReview && execution && state.latestExecutionReview.agentTaskExecutionId === execution.id ? state.latestExecutionReview : null;',
    '      const executionPullRequest = state.latestExecutionPullRequest;',
    '      const validationPolicy = state.latestExecutionValidationPolicy;',
    '      const replayValidation = state.latestReplayValidation;',
    '      if (!task) {',
    '        els.agentTaskPanel.className = "task-panel";',
    '        els.agentTaskPanel.innerHTML = [`<div class="result-card success"><strong>Review approved. Start the remediation handoff.</strong><div class="helper">Create an agent task against ${escapeHtml(selected.repository || "the approved repository")} using the approved report and linked GitHub draft.</div></div>`,`<label>Objective<textarea id="agentObjective" placeholder="Describe what the agent should investigate or fix.">${escapeHtml(defaultAgentTaskObjective(selected))}</textarea></label>`,`<div class="split"><label>Execution Mode<select id="agentExecutionMode"><option value="fix">Fix</option><option value="investigate">Investigate</option></select></label><label>Target Repository<input id="agentTargetRepository" value="${escapeHtml(selected.repository || "")}" /></label></div>`,`<label>Acceptance Criteria<textarea id="agentAcceptanceCriteria" placeholder="One acceptance criterion per line.">${escapeHtml(defaultAcceptanceCriteria(selected))}</textarea></label>`,`<label>Context Notes<textarea id="agentContextNotes" placeholder="Optional operator guidance for the agent.">Start from approved report ${escapeHtml(selected.reportId)} and linked GitHub draft context.</textarea></label>`,`<div class="task-actions"><button id="createAgentTask" class="primary">Start Agent Task</button></div>`].join("");',
    '      } else if (!execution) {',
    '        const executionSummary = execution ? `${execution.status}${executionDetail && executionDetail.branchName ? ` | branch ${executionDetail.branchName}` : ""}${executionDetail && executionDetail.baseBranch ? ` from ${executionDetail.baseBranch}` : ""}` : "No execution started yet.";',
    '        const latestResult = execution && execution.resultSummary && execution.resultSummary.nextAction ? execution.resultSummary.nextAction : "Awaiting execution.";',
    '        els.agentTaskPanel.className = "task-panel";',
    '        els.agentTaskPanel.innerHTML = [`<div class="task-status-grid">`,`<article class="task-status-card"><strong>Agent Task</strong><span>${escapeHtml(task.title || task.id)}</span><span>Status ${escapeHtml(task.status || "unknown")} | mode ${escapeHtml(task.executionMode || "fix")}</span></article>`,`<article class="task-status-card"><strong>Execution</strong><span>${escapeHtml(executionSummary)}</span><span>${escapeHtml(latestResult)}</span></article>`,`<article class="task-status-card"><strong>Repository</strong><span>${escapeHtml(selected.repository || "repository unresolved")}</span><span>${execution && execution.pullRequestUrl ? `<a href="${escapeHtml(execution.pullRequestUrl)}" target="_blank" rel="noreferrer">Open draft PR</a>` : "No PR opened yet."}</span></article>`,`</div>`,`<div class="task-actions"><button id="refreshAgentTask" class="secondary">Refresh Agent Status</button>${!execution && ["ready", "completed"].includes(task.status) ? `<button id="launchAgentExecution" class="primary">Launch Isolated Branch</button>` : ""}</div>`].join("");',
    '      } else {',
    '        const findings = executionDetail && Array.isArray(executionDetail.findings) ? executionDetail.findings : [];',
    '        const blockers = executionCloseout && Array.isArray(executionCloseout.blockers) ? executionCloseout.blockers : [];',
    '        const contract = executionCloseout && executionCloseout.contract ? executionCloseout.contract : {};',
    '        const gates = executionCloseout && executionCloseout.gates ? executionCloseout.gates : {};',
    '        const actualChangedFiles = contract && Array.isArray(contract.actualChangedFiles) ? contract.actualChangedFiles : [];',
    '        const contractWarnings = contract && Array.isArray(contract.warnings) ? contract.warnings : [];',
    '        const reviewStatusLabel = executionReview && executionReview.status ? executionReview.status : (gates.review && gates.review.status ? gates.review.status : "pending");',
    '        const reviewNotes = executionReview && executionReview.notes ? executionReview.notes : "";',
    '        const pullRequestUrl = executionPullRequest && executionPullRequest.pullRequestUrl ? executionPullRequest.pullRequestUrl : (executionDetail && executionDetail.pullRequestUrl ? executionDetail.pullRequestUrl : null);',
    '        const closeoutStatus = executionCloseout && executionCloseout.closeoutStatus ? executionCloseout.closeoutStatus : (executionDetail.status || "unknown");',
    '        const executionSummary = `${executionDetail.status || execution.status}${executionDetail.branchName ? ` | branch ${executionDetail.branchName}` : ""}${executionDetail.baseBranch ? ` from ${executionDetail.baseBranch}` : ""}`;',
    '        const nextAction = executionCloseout && executionCloseout.nextAction ? executionCloseout.nextAction : (executionDetail.resultSummary && executionDetail.resultSummary.nextAction ? executionDetail.resultSummary.nextAction : "Inspect execution details.");',
    '        const validationSummary = executionDetail.resultSummary && executionDetail.resultSummary.validationStatus ? executionDetail.resultSummary.validationStatus : (gates.validation && gates.validation.status ? gates.validation.status : "not-run");',
    '        const replaySummary = replayValidation && replayValidation.status ? replayValidation.status : (gates.replayValidation && gates.replayValidation.status ? gates.replayValidation.status : "not-run");',
    '        const promotionStatus = gates.promotion && gates.promotion.status ? gates.promotion.status : "not-applicable";',
    '        const mergeStatus = gates.merge && gates.merge.status ? gates.merge.status : "not-applicable";',
    '        const canReviewExecution = !["queued", "running"].includes(executionDetail.status || "");',
    '        const canPromoteExecution = promotionStatus === "ready";',
    '        els.agentTaskPanel.className = "task-panel";',
    '        els.agentTaskPanel.innerHTML = [`<div class="task-status-grid">`,`<article class="task-status-card"><strong>Agent Task</strong><span>${escapeHtml(task.title || task.id)}</span><span>Status ${escapeHtml(task.status || "unknown")} | mode ${escapeHtml(task.executionMode || "fix")}</span></article>`,`<article class="task-status-card"><strong>Execution</strong><span>${escapeHtml(executionSummary)}</span><span>${escapeHtml(nextAction)}</span></article>`,`<article class="task-status-card"><strong>Closeout</strong><span>Status ${escapeHtml(closeoutStatus)}</span><span>${escapeHtml(blockers.length ? blockers[0] : "No closeout blockers are currently reported.")}</span></article>`,`<article class="task-status-card"><strong>PR State</strong><span>${escapeHtml(valueOrFallback(executionPullRequest && executionPullRequest.status ? executionPullRequest.status : (pullRequestUrl ? "opened" : "not-opened"), "not-opened"))}</span><span>${pullRequestUrl ? `<a href="${escapeHtml(pullRequestUrl)}" target="_blank" rel="noreferrer">Open pull request</a>` : "No pull request opened yet."}</span></article>`,`</div>`,`<div class="detail-stack">`,`<article class="detail-card"><h3>Closeout Gates</h3><div class="gate-grid">${[["Contract", gates.agentOutputContract], ["Validation", gates.validation], ["Replay", gates.replayValidation], ["Review", gates.review], ["Promotion", gates.promotion], ["Merge", gates.merge]].map(([label, gate]) => `<div class="gate-card gate-${gateTone(gate && gate.status ? gate.status : "neutral")}"><strong>${escapeHtml(label)}</strong><span>Status ${escapeHtml(valueOrFallback(gate && gate.status ? gate.status : "not-run"))}</span><span>${escapeHtml(label === "Validation" && validationPolicy && validationPolicy.status ? `Policy ${validationPolicy.status}` : label === "Replay" && replayValidation && replayValidation.expectation ? `Expectation ${replayValidation.expectation}` : label === "Review" && executionReview && executionReview.reviewerId ? `Reviewer ${executionReview.reviewerId}` : label === "Promotion" && executionPullRequest && executionPullRequest.status ? `PR ${executionPullRequest.status}` : label === "Merge" && executionPullRequest && executionPullRequest.status ? `PR ${executionPullRequest.status}` : "")}</span></div>`).join("")}</div></article>`,`<div class="split">`,`<article class="detail-card"><h3>Findings</h3>${renderList(findings, "Execution findings have not been recorded yet.")}</article>`,`<article class="detail-card"><h3>Changed Files</h3>${renderList(actualChangedFiles, "No repository file changes were recorded for this execution.")}</article>`,`</div>`,`<div class="split">`,`<article class="detail-card"><h3>Validation Summary</h3><div class="helper">Validation ${escapeHtml(validationSummary)} | Replay ${escapeHtml(replaySummary)} | Contract ${escapeHtml(contract && contract.status ? contract.status : "not-run")}</div>${renderList(contractWarnings, "No contract warnings are currently recorded.")}</article>`,`<article class="detail-card"><h3>Closeout Blockers</h3>${renderList(blockers, "No closeout blockers are currently recorded.")}</article>`,`</div>`,`<div class="split">`,`<article class="detail-card"><h3>Execution Review</h3>${canReviewExecution ? `<label>Review Notes<textarea id="executionReviewNotes" placeholder="Record why this execution should be approved or rejected for promotion.">${escapeHtml(reviewNotes)}</textarea></label><div class="helper">Current status ${escapeHtml(reviewStatusLabel)}${executionReview && executionReview.reviewedAt ? ` | reviewed ${escapeHtml(relativeTime(executionReview.reviewedAt))}` : ""}</div><div class="task-actions"><button id="approveExecution" class="success">Approve Execution</button><button id="rejectExecution" class="danger">Reject Execution</button></div>` : `<div class="helper">Execution review unlocks after the run leaves queued or running state.</div>`}</article>`,`<article class="detail-card"><h3>Draft PR Promotion</h3><div class="helper">Promotion status ${escapeHtml(promotionStatus)} | merge status ${escapeHtml(mergeStatus)}</div><div class="helper">${escapeHtml(blockers.length ? blockers.join(" | ") : "Promotion is ready when review, validation, replay, and branch state are satisfied.")}</div><div class="task-actions"><button id="refreshAgentTask" class="secondary">Refresh Agent Status</button>${canPromoteExecution ? `<button id="promoteExecution" class="primary">Open Draft PR</button>` : ""}</div></article>`,`</div>`,`</div>`].join("");',
    '      }',
    '      const objective = document.getElementById("agentObjective");',
    '      const mode = document.getElementById("agentExecutionMode");',
    '      const repository = document.getElementById("agentTargetRepository");',
    '      const criteria = document.getElementById("agentAcceptanceCriteria");',
    '      const contextNotes = document.getElementById("agentContextNotes");',
    '      const createButton = document.getElementById("createAgentTask");',
    '      const refreshButton = document.getElementById("refreshAgentTask");',
    '      const launchButton = document.getElementById("launchAgentExecution");',
    '      const approveExecutionButton = document.getElementById("approveExecution");',
    '      const rejectExecutionButton = document.getElementById("rejectExecution");',
    '      const executionReviewNotes = document.getElementById("executionReviewNotes");',
    '      const promoteExecutionButton = document.getElementById("promoteExecution");',
    '      if (createButton) {',
    '        createButton.addEventListener("click", async () => {',
    '          const objectiveValue = objective && objective.value ? objective.value.trim() : "";',
    '          if (!objectiveValue) { setStatus("Agent task objective is required."); return; }',
    '          const payload = {',
    '            reportId: selected.reportId,',
    '            targetRepository: repository && repository.value ? repository.value.trim() : (selected.repository || undefined),',
    '            title: `Agent task for ${selected.title || selected.reportId}`,',
    '            objective: objectiveValue,',
    '            executionMode: mode && mode.value ? mode.value : "fix",',
    '            acceptanceCriteria: criteria && criteria.value ? criteria.value.split(/\\n+/).map((value) => value.trim()).filter(Boolean) : [],',
    '            contextNotes: contextNotes && contextNotes.value ? contextNotes.value.trim() : undefined',
    '          };',
    '          setStatus(`Creating agent task for ${selected.reportId}...`);',
    '          try {',
    '            const result = await request(`/internal/agent-tasks`, { method: "POST", headers: { "content-type": "application/json", ...authHeaders() }, body: JSON.stringify(payload) });',
    '            setStatus(`Agent task ${result.agentTaskId} queued. Waiting for preparation...`);',
    '            await pollAgentTask(result.agentTaskId);',
    '            await refreshSelectedContext();',
    '            renderAgentTaskPanel();',
    '            setStatus(`Agent task ${result.agentTaskId} prepared. Launch the isolated branch when ready.`);',
    '          } catch (error) {',
    '            setStatus(error instanceof Error ? error.message : "Failed to create agent task.");',
    '          }',
    '        });',
    '      }',
    '      if (refreshButton) {',
    '        refreshButton.addEventListener("click", async () => {',
    '          setStatus(`Refreshing agent status for ${selected.reportId}...`);',
    '          try {',
    '            await refreshSelectedContext();',
    '            renderAgentTaskPanel();',
    '            setStatus(`Refreshed agent status for ${selected.reportId}.`);',
    '          } catch (error) {',
    '            setStatus(error instanceof Error ? error.message : "Failed to refresh agent status.");',
    '          }',
    '        });',
    '      }',
    '      if (launchButton && task) {',
    '        launchButton.addEventListener("click", async () => {',
    '          setStatus(`Launching isolated branch for agent task ${task.id}...`);',
    '          try {',
    '            const result = await request(`/internal/agent-tasks/${task.id}/execute`, { method: "POST", headers: authHeaders() });',
    '            state.latestExecutionDetail = await pollExecution(result.executionId);',
    '            await refreshSelectedContext();',
    '            renderAgentTaskPanel();',
    '            setStatus(`Execution ${result.executionId} started. Inspect the agent handoff panel for branch status.`);',
    '          } catch (error) {',
    '            setStatus(error instanceof Error ? error.message : "Failed to launch isolated branch.");',
    '          }',
    '        });',
    '      }',
    '      const submitExecutionReview = async (status) => {',
    '        if (!executionDetail) return;',
    '        const notesValue = executionReviewNotes && executionReviewNotes.value ? executionReviewNotes.value.trim() : "";',
    '        if (!notesValue) { setStatus("Execution review requires explicit notes."); return; }',
    '        setStatus(`${status === "approved" ? "Approving" : "Rejecting"} execution ${executionDetail.id}...`);',
    '        try {',
    '          await request(`/internal/agent-task-executions/${executionDetail.id}/review`, { method: "POST", headers: { "content-type": "application/json", ...authHeaders() }, body: JSON.stringify({ status, notes: notesValue }) });',
    '          await refreshSelectedContext();',
    '          renderAgentTaskPanel();',
    '          setStatus(`Execution ${executionDetail.id} marked ${status}.`);',
    '        } catch (error) {',
    '          setStatus(error instanceof Error ? error.message : "Failed to submit execution review.");',
    '        }',
    '      };',
    '      if (approveExecutionButton) {',
    '        approveExecutionButton.addEventListener("click", () => submitExecutionReview("approved"));',
    '      }',
    '      if (rejectExecutionButton) {',
    '        rejectExecutionButton.addEventListener("click", () => submitExecutionReview("rejected"));',
    '      }',
    '      if (promoteExecutionButton && executionDetail) {',
    '        promoteExecutionButton.addEventListener("click", async () => {',
    '          setStatus(`Opening draft PR for execution ${executionDetail.id}...`);',
    '          try {',
    '            const result = await request(`/internal/agent-task-executions/${executionDetail.id}/promote`, { method: "POST", headers: { "content-type": "application/json", ...authHeaders() }, body: JSON.stringify({ draft: true }) });',
    '            await refreshSelectedContext();',
    '            renderAgentTaskPanel();',
    '            setStatus(result && result.pullRequestUrl ? `Draft PR opened for execution ${executionDetail.id}.` : `Execution ${executionDetail.id} promoted to draft PR.`);',
    '          } catch (error) {',
    '            setStatus(error instanceof Error ? error.message : "Failed to open draft PR.");',
    '          }',
    '        });',
    '      }',
    '    }',
    '    function buildOperatorSummary(selected, context) {',
    '      if (!selected || !context) {',
    '        return `<div class="empty">Load a report to see the decision-ready summary before the raw JSON.</div>`;',
    '      }',
    '      const report = context.report || {};',
    '      const draft = context.draft || {};',
    '      const review = context.reportReview || null;',
    '      const impact = context.impact || {};',
    '      const classification = context.classification || {};',
    '      const developerSummary = context.developerSummary || {};',
    '      const payload = context.observabilityContext && context.observabilityContext.payload ? context.observabilityContext.payload : {};',
    '      const artifacts = payload.artifacts || {};',
    '      const history = context.history && context.history.summary ? context.history.summary : {};',
    '      const duplicateCount = context.duplicates && Array.isArray(context.duplicates.candidates) ? context.duplicates.candidates.length : 0;',
    '      const artifactFlags = [artifacts.hasHar ? "HAR" : null, artifacts.hasConsoleLogs ? "console logs" : null, artifacts.hasScreenRecording ? "screen recording" : null, artifacts.hasLocalStorageSnapshot ? "local storage" : null, artifacts.hasSessionStorageSnapshot ? "session storage" : null].filter(Boolean).join(", ") || "No artifacts attached";',
    '      const submittedImpact = typeof payload.impactScore === "number" ? payload.impactScore : null;',
    '      const currentImpact = typeof impact.score === "number" ? impact.score : submittedImpact;',
    '      return [`<div class="insight-grid">`,`<article class="insight-card"><strong>Decision</strong><span>${escapeHtml(report.source || "unknown source")} | ${escapeHtml(report.severity || selected.severity || "unknown severity")} | review ${escapeHtml(review && review.status ? review.status : selected.reviewStatus || "pending")}</span><span>${escapeHtml((classification.primaryIntent || "report") + (classification.confidence ? ` (${Math.round(classification.confidence * 100)}% confidence)` : ""))}</span></article>`,`<article class="insight-card"><strong>Routing</strong><span>Repository ${escapeHtml(draft.repository || selected.repository || "unresolved")}</span><span>Top owner ${escapeHtml(developerSummary.topOwner || (selected.owner && selected.owner.label) || "unresolved")}</span><span>Next action ${escapeHtml(developerSummary.nextAction || "inspect-report-context")}</span></article>`,`<article class="insight-card"><strong>Impact</strong><span>Current ${escapeHtml(String(currentImpact ?? "n/a"))}${impact.band ? ` | ${escapeHtml(impact.band)}` : ""}</span><span>${submittedImpact !== null && submittedImpact !== currentImpact ? `Submitted ${escapeHtml(String(submittedImpact))}` : "Submitted and current impact align"}</span></article>`,`<article class="insight-card"><strong>Evidence</strong><span>${escapeHtml(artifactFlags)}</span><span>${escapeHtml(String(duplicateCount))} duplicate candidates | ${escapeHtml(String(history.relatedIssueCount ?? 0))} related issues</span></article>`,`<article class="insight-card"><strong>Reporter</strong><span>${escapeHtml(report.reporterIdentifier || selected.reporterIdentifier || "anonymous")}</span><span>${escapeHtml(payload.environment || "environment unknown")} | ${escapeHtml(payload.pageUrl || "page URL unavailable")}</span></article>`,`<article class="insight-card"><strong>GitHub Draft</strong><span>State ${escapeHtml(draft.state || selected.draftState || "unknown")}</span><span>${draft.issueUrl ? `<a href="${escapeHtml(draft.issueUrl)}" target="_blank" rel="noreferrer">Open linked draft</a>` : escapeHtml(context.syncError || selected.syncError || "No linked GitHub draft yet")}</span></article>`,`</div>`].join("");',
    '    }',
    '    function renderGuardrails() {',
    '      const repositoryTarget = els.repository.value.trim() || (state.selected && state.selected.repository) || "";',
    '      if (isReviewedSelection()) {',
    '        renderGuardrailCard(els.guardrailTarget, "pass", "Review already completed", `This report was ${state.selected.reviewStatus}. Inspect it from reviewed history, not the pending queue.`);',
    '        renderGuardrailCard(els.guardrailContext, state.context ? "pass" : "neutral", state.context ? "Evidence is loaded" : "Evidence not loaded", state.context ? "This reviewed report is still inspectable." : "Select a reviewed report to inspect its evidence.");',
    '        renderGuardrailCard(els.guardrailRationale, "pass", "Decision notes were captured", "Use reviewed history for audit and follow-up rather than editing the completed decision here.");',
    '        renderGuardrailCard(els.guardrailPromotion, "pass", "Pending queue action is complete", "This report has already moved through the review gate.");',
    '        els.approve.disabled = true;',
    '        els.reject.disabled = true;',
    '        return;',
    '      }',
    '      renderGuardrailCard(els.guardrailTarget, state.selected && repositoryTarget ? "pass" : state.selected ? "fail" : "neutral", state.selected && repositoryTarget ? "Repository target is ready" : state.selected ? "Repository target is missing" : "No report selected", state.selected && repositoryTarget ? `This review will target ${repositoryTarget}.` : state.selected ? "Choose the repository target before approving downstream GitHub work." : "Pick a report before you decide anything.");',
    '      renderGuardrailCard(els.guardrailContext, state.context ? "pass" : state.selected ? "fail" : "neutral", state.context ? "Evidence is loaded" : state.selected ? "Evidence is still loading" : "Evidence not loaded", state.context ? "Evidence and review history are visible for this report." : state.selected ? "Wait for the evidence load before approving or rejecting this report." : "Select a report to inspect evidence.");',
    '      renderGuardrailCard(els.guardrailRationale, els.notes.value.trim() ? "pass" : state.selected ? "fail" : "neutral", els.notes.value.trim() ? "Decision notes are ready" : state.selected ? "Decision notes are missing" : "No notes needed yet", els.notes.value.trim() ? "Operator notes are present for the next action." : state.selected ? "Add notes before approving or rejecting the selected report." : "Notes become required once a report is selected.");',
    '      renderGuardrailCard(els.guardrailPromotion, canApproveSelection() ? "pass" : state.selected ? "fail" : "neutral", canApproveSelection() ? "Approval is unblocked" : state.selected ? "Approval is still blocked" : "Approval is idle", canApproveSelection() ? "Approval can proceed because target, evidence, and notes are all visible." : state.selected ? "Approval stays blocked until repository target, evidence, and notes are all present." : "Choose a report before acting.");',
    '      els.approve.disabled = !canApproveSelection();',
    '      els.reject.disabled = !canRejectSelection();',
    '    }',
    '    function renderSummary() {',
    '      const summary = state.summary;',
    '      const filters = state.filters;',
    '      const severityCounts = summary && summary.severityCounts ? summary.severityCounts : {};',
    '      const workflow = summary && summary.workflow ? summary.workflow : null;',
    '      const projectSummaries = summary && Array.isArray(summary.projectSummaries) ? summary.projectSummaries : [];',
    '      els.queuedCount.textContent = String(summary ? summary.totalItems : 0);',
    '      els.criticalCount.textContent = String(severityCounts.critical || 0);',
    '      els.projectCount.textContent = String(projectSummaries.length);',
    '      els.pageValue.textContent = String(filters.page);',
    '      els.pageNote.textContent = `${filters.sort} order | ${state.selectedIds.length} selected`;',
    '      els.queuedNote.textContent = summary ? `${summary.totalPages} page${summary.totalPages === 1 ? "" : "s"} in current queue filter.` : "Pending reports across the current filter.";',
    '      const severityText = Object.entries(severityCounts).length ? Object.entries(severityCounts).map(([key, value]) => `${key}: ${value}`).join(" | ") : "No queue data loaded yet.";',
    '      els.severitySummary.textContent = severityText;',
    '      const activeFilters = [filters.projectId ? `project ${filters.projectId}` : null, filters.assignedTo ? `assigned ${filters.assignedTo}` : null, filters.search ? `search \"${filters.search}\"` : null].filter(Boolean).join(" | ") || "No filters applied.";',
    '      els.filterSummary.textContent = activeFilters;',
    '      els.windowSummary.textContent = summary ? `${state.items.length} item${state.items.length === 1 ? "" : "s"} shown on page ${filters.page} of ${summary.totalPages}.` : "Waiting for queue data.";',
    '      els.workflowSummary.textContent = workflow ? `assigned ${workflow.assignedCount} | unassigned ${workflow.unassignedCount} | stale ${workflow.staleCount} | oldest ${workflow.oldestPendingAgeHours}h | avg ${workflow.averageAgeHours}h` : "No queue data loaded yet.";',
    '      els.pageSummary.textContent = summary ? `Page ${filters.page} of ${summary.totalPages}` : `Page ${filters.page}`;',
    '      els.previousPage.disabled = filters.page <= 1;',
    '      els.nextPage.disabled = !(summary && summary.hasNextPage);',
    '      els.projectSummaries.innerHTML = "";',
    '      const allButton = document.createElement("button");',
    '      allButton.type = "button";',
    '      allButton.className = `project-pill${filters.projectId ? "" : " active"}`;',
    '      allButton.textContent = `All projects (${summary ? summary.totalItems : 0})`;',
    '      allButton.addEventListener("click", () => { state.filters.page = 1; els.projectId.value = ""; loadQueue(); });',
    '      els.projectSummaries.appendChild(allButton);',
    '      for (const entry of projectSummaries) {',
    '        const button = document.createElement("button");',
    '        button.type = "button";',
    '        const projectId = entry.project && entry.project.id ? entry.project.id : "";',
    '        button.className = `project-pill${projectId && projectId === filters.projectId ? " active" : ""}`;',
    '        button.innerHTML = `<strong>${escapeHtml(entry.project ? entry.project.name : "Unscoped")}</strong><br /><span class="helper">${entry.queuedCount} queued | impact ${entry.highestImpactScore ?? "n/a"}</span>`;',
    '        button.addEventListener("click", () => { state.filters.page = 1; els.projectId.value = projectId; loadQueue(); });',
    '        els.projectSummaries.appendChild(button);',
    '      }',
    '    }',
    '    function renderQueue() {',
    '      els.queue.innerHTML = "";',
    '      if (!state.items.length) {',
    '        const empty = document.createElement("div");',
    '        empty.className = "empty";',
    '        empty.textContent = "No reports are waiting for review in this filter.";',
    '        els.queue.appendChild(empty);',
    '        return;',
    '      }',
    '      for (const item of state.items) {',
    '        const card = document.createElement("button");',
    '        card.type = "button";',
    '        card.className = `item${state.selected && state.selected.reportId === item.reportId ? " active" : ""}`;',
    '        card.innerHTML = [`<div class="item-header"><input class="item-check" data-role="select" type="checkbox" ${isSelected(item.reportId) ? "checked" : ""} /><div><h3>${escapeHtml(item.title || item.reportId)}</h3><div class="meta"><span class="badge">${escapeHtml(item.project ? item.project.name : "Unscoped project")}</span><span class="badge">${escapeHtml(item.severity)}</span><span class="badge">impact ${item.impactScore ?? "n/a"}</span><span class="badge">${escapeHtml(relativeTime(item.createdAt))}</span></div><div class="helper">${escapeHtml(item.repository || "repository unresolved")} | owner ${escapeHtml(item.owner ? item.owner.label : "unresolved")} | ${escapeHtml(item.reporterIdentifier || "anonymous")} | assigned ${escapeHtml(item.assignedReviewerId || "unassigned")}</div></div></div>`].join("");',
    '        const checkbox = card.querySelector("[data-role=select]");',
    '        if (checkbox) { checkbox.addEventListener("click", (event) => { event.stopPropagation(); }); checkbox.addEventListener("change", () => toggleSelection(item.reportId)); }',
    '        card.addEventListener("click", () => selectItem(item));',
    '        els.queue.appendChild(card);',
    '      }',
    '    }',
    '    function renderSelection() {',
    '      const selected = state.selected;',
    '      const context = state.context;',
    '      if (!selected) {',
    '        els.summary.className = "empty";',
    '        els.summary.textContent = "Select a report to inspect its details.";',
    '        renderAgentTaskPanel();',
    '        els.contextSummary.className = "empty";',
    '        els.contextSummary.textContent = "Load a report to see the decision-ready summary before the raw JSON.";',
    '        els.context.textContent = "// report evidence appears here";',
    '        els.reviewActivity.innerHTML = `<div class="empty">Select a report to inspect its review history.</div>`;',
    '        renderDecisionResult();',
    '        renderGuardrails();',
    '        return;',
    '      }',
    '      els.summary.className = "";',
    '      els.summary.innerHTML = [`<div class="row">`,`<span class="badge">${escapeHtml(selected.reportId)}</span>`,`<span class="badge">${escapeHtml(selected.repository || "repository unresolved")}</span>`,`<span class="badge">${escapeHtml(selected.severity)}</span>`,`<span class="badge">owner ${escapeHtml(selected.owner ? selected.owner.label : "unresolved")}</span>`,`<span class="badge">assigned ${escapeHtml(selected.assignedReviewerId || "unassigned")}</span>`, selected.reviewStatus ? `<span class="badge">review ${escapeHtml(selected.reviewStatus)}</span>` : "", selected.draftState ? `<span class="badge">draft ${escapeHtml(selected.draftState)}</span>` : "", `</div>`,`<p><strong>${escapeHtml(selected.title)}</strong></p>`,`<p>${selected.project ? `${escapeHtml(selected.project.name)} (${escapeHtml(selected.project.projectKey)})` : "No project metadata"}</p>`,`<p>Reporter: ${escapeHtml(selected.reporterIdentifier || "anonymous")}</p>`,`<p class="helper">Created ${escapeHtml(relativeTime(selected.createdAt))} | Updated ${escapeHtml(relativeTime(selected.updatedAt))}</p>`].join("");',
    '      els.repository.value = selected.repository || "";',
    '      renderAgentTaskPanel();',
    '      els.contextSummary.className = "";',
    '      els.contextSummary.innerHTML = buildOperatorSummary(selected, context);',
    '      els.context.textContent = JSON.stringify(context || {}, null, 2);',
    '      const reviewActivity = Array.isArray(context && context.reviewActivity) ? context.reviewActivity : [];',
    '      els.reviewActivity.innerHTML = reviewActivity.length ? reviewActivity.map((entry) => [`<article class="timeline-entry">`,`<strong>${escapeHtml(entry.summary || entry.eventType || "Activity")}</strong>`,`<div class="helper">${escapeHtml(entry.eventType || "unknown")} | ${escapeHtml(relativeTime(entry.createdAt))} | actor ${escapeHtml(entry.actorId || entry.actorType || "unknown")}</div>`,`</article>`].join("")).join("") : `<div class="empty">No review activity has been recorded yet.</div>`;',
    '      renderDecisionResult();',
    '      renderGuardrails();',
    '    }',
    '    async function loadQueue() {',
    '      saveAuth();',
    '      setStatus("Loading reports waiting for review...");',
    '      state.filters.projectId = els.projectId.value.trim();',
    '      state.filters.assignedTo = els.assignedTo.value.trim();',
    '      state.filters.search = els.search.value.trim();',
    '      state.filters.sort = els.sort.value;',
    '      const params = new URLSearchParams();',
    '      if (state.filters.projectId) params.set("projectId", state.filters.projectId);',
    '      if (state.filters.assignedTo) params.set("assignedTo", state.filters.assignedTo);',
    '      if (state.filters.search) params.set("search", state.filters.search);',
    '      params.set("page", String(state.filters.page));',
    '      params.set("limit", String(state.filters.limit));',
    '      params.set("sort", state.filters.sort);',
    '      try {',
    '        const data = await request(`/internal/reports/review-queue?${params.toString()}`, { headers: authHeaders() });',
    '        state.items = Array.isArray(data.items) ? data.items : [];',
    '        state.summary = data.summary || null;',
    '        state.selectedIds = state.selectedIds.filter((reportId) => state.items.some((item) => item.reportId === reportId));',
    '        state.filters.page = data.filters && typeof data.filters.page === "number" ? data.filters.page : state.filters.page;',
    '        if (state.selected) {',
    '          state.selected = state.items.find((item) => item.reportId === state.selected.reportId) || null;',
    '        }',
    '        renderSummary();',
    '        renderQueue();',
    '        renderReviewedHistory();',
    '        renderSelection();',
    '        setStatus(`Loaded ${state.items.length} report${state.items.length === 1 ? "" : "s"} on page ${state.filters.page}.`);',
    '      } catch (error) {',
    '        state.summary = null;',
    '        renderSummary();',
    '        renderGuardrails();',
    '        setStatus(error instanceof Error ? error.message : "Failed to load queue.");',
    '      }',
    '    }',
    '    async function selectItem(item) {',
    '      state.selected = item;',
    '      state.latestExecutionDetail = null;',
    '      renderQueue();',
    '      setStatus(`Loading evidence for ${item.reportId}...`);',
    '      try {',
    '        await refreshSelectedContext();',
    '        renderSelection();',
    '        setStatus(`Loaded evidence for ${item.reportId}.`);',
    '      } catch (error) {',
    '        state.context = null;',
    '        renderSelection();',
    '        setStatus(error instanceof Error ? error.message : "Failed to load report evidence.");',
    '      }',
    '    }',
    '    async function submitReview(status) {',
    '      if (!state.selected) return;',
    '      setStatus(`${status === "approved" ? "Approving" : "Rejecting"} ${state.selected.reportId}...`);',
    '      try {',
    '        const selectedItem = state.selected;',
    '        const payload = { status, notes: els.notes.value.trim() || undefined, repository: status === "approved" ? (els.repository.value.trim() || undefined) : undefined };',
    '        const result = await request(`/internal/reports/${state.selected.reportId}/review`, { method: "POST", headers: { "content-type": "application/json", ...authHeaders() }, body: JSON.stringify(payload) });',
    '        const reviewedItem = { ...selectedItem, repository: result && result.draft && result.draft.repository ? result.draft.repository : selectedItem.repository, assignedReviewerId: result && result.review && result.review.reviewerId ? result.review.reviewerId : selectedItem.assignedReviewerId, reviewStatus: result && result.review && result.review.status ? result.review.status : status, draftState: result && result.draft && result.draft.state ? result.draft.state : (status === "approved" ? "local-draft" : "rejected"), issueUrl: result && result.draft && result.draft.issueUrl ? result.draft.issueUrl : null, issueNumber: result && result.draft && result.draft.issueNumber ? result.draft.issueNumber : null, syncError: result && result.syncError ? result.syncError : null, reviewedAt: result && result.review && result.review.reviewedAt ? result.review.reviewedAt : new Date().toISOString() };',
    '        state.lastDecision = { reportId: reviewedItem.reportId, repository: reviewedItem.repository, reviewStatus: reviewedItem.reviewStatus, draftState: reviewedItem.draftState, issueUrl: reviewedItem.issueUrl, reviewedAt: reviewedItem.reviewedAt, syncError: reviewedItem.syncError, message: status === "approved" ? (reviewedItem.issueUrl ? "GitHub draft created and the item moved out of the pending queue." : "Approval recorded. The item moved out of the pending queue.") : "Rejection recorded. The item moved out of the pending queue." };',
    '        saveLastDecision();',
    '        upsertReviewedItem(reviewedItem);',
    '        els.notes.value = "";',
    '        await loadQueue();',
    '        state.selected = reviewedItem;',
    '        try {',
    '          state.context = await request(reviewedItem.contextPath, { headers: authHeaders() });',
    '        } catch {',
    '          state.context = null;',
    '        }',
    '        renderReviewedHistory();',
    '        renderSelection();',
    '        setStatus(status === "approved" ? `Approved ${reviewedItem.reportId}. Inspect the handoff details below.` : `Rejected ${reviewedItem.reportId}. Inspect the handoff details below.`);',
    '      } catch (error) {',
    '        setStatus(error instanceof Error ? error.message : "Failed to submit review.");',
    '      }',
    '    }',
    '    async function submitBulkAction(action) {',
    '      if (!state.selectedIds.length) { setStatus("Select at least one report first."); return; }',
    '      setStatus(`${action} ${state.selectedIds.length} report(s)...`);',
    '      const notes = els.bulkNotes.value.trim() || undefined;',
    '      const explicitRepository = els.bulkRepository.value.trim();',
    '      const sharedRepository = resolveSharedSelectedRepository();',
    '      const repository = action === "approve" ? (explicitRepository || sharedRepository || undefined) : undefined;',
    '      if (!notes) {',
    '        setStatus(action === "assign" ? "Bulk assignment requires notes." : "Bulk review decisions require notes.");',
    '        return;',
    '      }',
    '      if (action === "approve" && !repository) {',
    '        setStatus("Bulk approval requires a repository override unless every selected report shares the same repository.");',
    '        return;',
    '      }',
    '      const payload = {',
    '        action,',
    '        reportIds: state.selectedIds,',
    '        reviewerId: action === "assign" ? (els.bulkReviewerId.value.trim() || undefined) : undefined,',
    '        repository,',
    '        notes',
    '      };',
    '      try {',
    '        await request(`/internal/reports/review-queue/actions`, { method: "POST", headers: { "content-type": "application/json", ...authHeaders() }, body: JSON.stringify(payload) });',
    '        els.bulkNotes.value = "";',
    '        if (action !== "assign") { els.bulkRepository.value = ""; }',
    '        clearSelection();',
    '        await loadQueue();',
    '        setStatus(`Bulk ${action} completed.`);',
    '      } catch (error) {',
    '        setStatus(error instanceof Error ? error.message : `Bulk ${action} failed.`);',
    '      }',
    '    }',
    '    const saved = readSaved();',
    '    state.reviewedItems = readReviewedHistory();',
    '    state.lastDecision = readLastDecision();',
    '    els.baseUrl.value = saved.baseUrl || window.location.origin;',
    '    els.token.value = saved.token || "";',
    '    els.projectId.value = saved.projectId || "";',
    '    els.assignedTo.value = saved.assignedTo || "";',
    '    els.search.value = saved.search || "";',
    '    els.sort.value = saved.sort || "newest";',
    '    state.filters.projectId = els.projectId.value.trim();',
    '    state.filters.assignedTo = els.assignedTo.value.trim();',
    '    state.filters.search = els.search.value.trim();',
    '    state.filters.sort = els.sort.value;',
    '    els.refresh.addEventListener("click", () => { state.filters.page = 1; loadQueue(); });',
    '    els.clearToken.addEventListener("click", () => { localStorage.removeItem(storageKey); els.token.value = ""; setStatus("Saved auth cleared."); });',
    '    els.previousPage.addEventListener("click", () => { if (state.filters.page > 1) { state.filters.page -= 1; loadQueue(); } });',
    '    els.nextPage.addEventListener("click", () => { state.filters.page += 1; loadQueue(); });',
    '    els.assignedTo.addEventListener("keydown", (event) => { if (event.key === "Enter") { state.filters.page = 1; loadQueue(); } });',
    '    els.search.addEventListener("keydown", (event) => { if (event.key === "Enter") { state.filters.page = 1; loadQueue(); } });',
    '    els.sort.addEventListener("change", () => { state.filters.page = 1; loadQueue(); });',
    '    els.notes.addEventListener("input", renderGuardrails);',
    '    els.repository.addEventListener("input", renderGuardrails);',
    '    els.approve.addEventListener("click", () => submitReview("approved"));',
    '    els.reject.addEventListener("click", () => submitReview("rejected"));',
    '    els.assignSelected.addEventListener("click", () => submitBulkAction("assign"));',
    '    els.approveSelected.addEventListener("click", () => submitBulkAction("approve"));',
    '    els.rejectSelected.addEventListener("click", () => submitBulkAction("reject"));',
    '    els.clearSelection.addEventListener("click", clearSelection);',
    '    renderSummary();',
    '    renderReviewedHistory();',
    '    renderDecisionResult();',
    '    renderGuardrails();',
    '  </script>',
    '</body>',
    '</html>'
  ].join('\n');
}